import type React from 'react';
import {
  BadgeDollarSign,
  BookOpen,
  Bug,
  Building2,
  Calculator,
  Calendar,
  ClipboardList,
  Code,
  CreditCard,
  Database,
  FileText,
  FlaskConical,
  GraduationCap,
  Heart,
  Headphones,
  HeartHandshake,
  IndianRupee,
  MessageCircle,
  PenTool,
  PhoneCall,
  Plus,
  Receipt,
  RefreshCw,
  ScanSearch,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Target,
  UserPlus,
  UserSearch,
  Users,
  Wallet,
  Truck,
} from 'lucide-react';

export interface AgentTemplate {
  id: string;
  name: string;
  type: string;
  industry: string;
  description: string;
  businessPurpose?: string;
  features: string[];
  // Model id from the gateway (ex: "openai/gpt-4o"). This can be overridden at deploy-time.
  model: string;
  platform: string;
  budget: number;
  price: string;
  icon: React.ElementType;
  color: string;
  roi?: string;
  complexity?: 'Basic' | 'Advanced' | 'Expert';
  maturity?: 'Core' | 'Beta' | 'Preview';
  riskLevel?: 'Low' | 'Medium' | 'High';
  approvalDefault?: string;
  requiredSystems?: string[];
  samplePrompts?: string[];
  certifications?: string[];   // e.g. ['DPDP', 'GDPR', 'ISO 42001', 'SEBI', 'RBI', 'HIPAA']
  usedBy?: number;             // number of teams using this template
  setupMinutes?: number;       // estimated setup time in minutes
}

export const AGENT_TEMPLATE_INDUSTRIES = [
  'all',
  'HR',
  'Enterprise',
  'E-commerce',
  'B2B',
  'Legal',
  'Banking',
  'Technology',
  'Healthcare',
  'Finance',
  'India',
] as const;

export const AGENT_TEMPLATES: AgentTemplate[] = [
  // ── HR-first templates ────────────────────────────────────────────────────
  {
    id: 'hr-benefits',
    name: 'Benefits Navigator',
    type: 'hr_benefits',
    industry: 'HR',
    description: 'Instantly answers employee questions about health insurance, dental, pension, and benefits enrollment — 24/7, without waiting for an HR email.',
    features: ['Benefits FAQ', 'Enrollment Guidance', 'Policy Explainers', 'Open Enrollment Reminders', 'Claims Support'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1500,
    price: '₹18,000/month',
    icon: Heart,
    color: 'rose',
    roi: 'Reduces benefits-related HR tickets by 60%',
    complexity: 'Basic',
    certifications: ['DPDP', 'ISO 42001'],
    usedBy: 291,
    setupMinutes: 5,
  },
  {
    id: 'hr-onboarding',
    name: 'Onboarding Assistant',
    type: 'hr_onboarding',
    industry: 'HR',
    description: 'Guides new hires through their entire first 30 days — paperwork, introductions, tool access, and manager check-ins — automatically.',
    businessPurpose: 'Coordinate onboarding steps, collect documents, and trigger governed access requests with a clean audit trail.',
    features: ['Day-1 Checklist', 'Document Collection', 'Tool Access Requests', '30/60/90 Day Plans', 'Manager Nudges'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1200,
    price: '₹15,000/month',
    icon: UserPlus,
    color: 'cyan',
    roi: 'Cuts onboarding admin time by 70%',
    complexity: 'Basic',
    maturity: 'Core',
    riskLevel: 'Medium',
    approvalDefault: 'Manager approval for access changes; advisory-only for reminders and checklists',
    requiredSystems: ['HRIS or employee directory', 'Email or chat', 'Access management'],
    samplePrompts: [
      'Create a day-one checklist for a new engineer joining next Monday.',
      'Draft the access requests needed for a sales manager in Mumbai.',
    ],
    certifications: ['DPDP', 'ISO 42001'],
    usedBy: 847,
    setupMinutes: 10,
  },
  {
    id: 'hr-payroll',
    name: 'Payroll Bot',
    type: 'hr_payroll',
    industry: 'HR',
    description: 'Handles all payslip queries, tax deduction questions, reimbursement status, and payroll discrepancy reports — without pulling HR into every conversation.',
    features: ['Payslip Explainers', 'Tax Form Guidance', 'Reimbursement Status', 'Deduction Breakdown', 'Escalation Routing'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹22,000/month',
    icon: BadgeDollarSign,
    color: 'amber',
    roi: 'Handles 80% of payroll queries without HR intervention',
    complexity: 'Basic',
    certifications: ['DPDP', 'RBI'],
    usedBy: 423,
    setupMinutes: 15,
  },
  {
    id: 'hr-leave',
    name: 'Leave & Attendance Manager',
    type: 'hr_leave',
    industry: 'HR',
    description: 'Processes leave requests, checks balances, flags attendance anomalies, and notifies managers — keeping HR out of the back-and-forth.',
    features: ['Leave Balance Checks', 'Request Processing', 'Attendance Anomaly Alerts', 'Manager Notifications', 'Policy Enforcement'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1000,
    price: '₹12,000/month',
    icon: Calendar,
    color: 'teal',
    roi: 'Saves HR 10+ hours per week on leave admin',
    complexity: 'Basic',
    certifications: ['DPDP'],
    usedBy: 318,
    setupMinutes: 5,
  },
  {
    id: 'hr-policy',
    name: 'Policy Advisor',
    type: 'hr_policy',
    industry: 'HR',
    description: 'Gives employees instant, accurate answers to HR policy questions — code of conduct, expense claims, remote work rules — with full audit trail.',
    businessPurpose: 'Deliver governed policy answers with escalation when the request goes beyond documented rules.',
    features: ['Policy Q&A', 'Expense Guidelines', 'Remote Work Rules', 'Code of Conduct FAQs', 'Audit Trail'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1200,
    price: '₹14,000/month',
    icon: BookOpen,
    color: 'violet',
    roi: 'Reduces policy-related interruptions to HR by 50%',
    complexity: 'Basic',
    maturity: 'Core',
    riskLevel: 'Low',
    approvalDefault: 'Answer directly; escalate only for policy exceptions or missing guidance',
    requiredSystems: ['Policy repository', 'Employee directory'],
    samplePrompts: [
      'What is our reimbursement policy for home internet?',
      'When does remote work need manager approval?',
    ],
    certifications: ['DPDP', 'ISO 42001'],
    usedBy: 612,
    setupMinutes: 5,
  },
  // ── Broader domain templates ───────────────────────────────────────────────
  {
    id: '1',
    name: 'Support Agent',
    type: 'customer_support',
    industry: 'E-commerce',
    description: 'AI-powered customer support agent for handling inquiries, order tracking, and common questions.',
    businessPurpose: 'Resolve routine support queries, keep risky credits behind approval, and leave evidence on every customer-facing answer.',
    features: ['Order Status Lookup', 'Refund Processing', 'Product Information', 'FAQ Automation', 'Escalation Routing'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹25,000/month',
    icon: Headphones,
    color: 'blue',
    maturity: 'Core',
    riskLevel: 'Medium',
    approvalDefault: 'Auto-answer FAQs; require approval for refunds, credits, and policy exceptions',
    requiredSystems: ['Helpdesk', 'Order management', 'Knowledge base'],
    samplePrompts: [
      'Where is order #84219 and when will it arrive?',
      'Can you process a refund for a damaged shipment?',
    ],
    certifications: ['DPDP', 'ISO 42001'],
    usedBy: 1247,
    setupMinutes: 8,
  },
  {
    id: '2',
    name: 'Sales Agent',
    type: 'sales',
    industry: 'B2B',
    description: 'Intelligent sales assistant for lead qualification, demo scheduling, and product recommendations.',
    businessPurpose: 'Qualify inbound leads, draft follow-ups, and enforce approval before discounting or commitments.',
    features: ['Lead Qualification', 'Demo Scheduling', 'Product Recommendations', 'CRM Integration', 'Follow-up Automation'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹35,000/month',
    icon: Target,
    color: 'green',
    maturity: 'Core',
    riskLevel: 'Medium',
    approvalDefault: 'Auto-draft outreach; require approval for pricing, discounts, and contract terms',
    requiredSystems: ['CRM', 'Calendar', 'Email'],
    samplePrompts: [
      'Qualify this inbound lead and draft a follow-up email.',
      'Prepare a demo handoff summary for the account executive.',
    ],
    certifications: ['ISO 42001'],
    usedBy: 534,
    setupMinutes: 12,
  },
  {
    id: '3',
    name: 'HR Agent',
    type: 'hr',
    industry: 'Enterprise',
    description: 'HR assistant for employee onboarding, policy queries, and leave management.',
    features: ['Employee Onboarding', 'Policy FAQ', 'Leave Management', 'Benefits Information', 'Performance Reviews'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1500,
    price: '₹20,000/month',
    icon: Users,
    color: 'purple',
  },
  {
    id: '4',
    name: 'Legal Agent',
    type: 'legal',
    industry: 'Legal',
    description: 'Legal document assistant for contract review, compliance checking, and risk assessment.',
    businessPurpose: 'Review clauses, surface legal risk, and prepare escalations without letting AI silently approve contract language.',
    features: ['Contract Review', 'Compliance Check', 'Risk Assessment', 'Document Summarization', 'Clause Analysis'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 5000,
    price: '₹50,000/month',
    icon: ShieldCheck,
    color: 'red',
    maturity: 'Core',
    riskLevel: 'High',
    approvalDefault: 'Always require legal approval before any outward recommendation or contract action',
    requiredSystems: ['Document repository', 'Clause library'],
    samplePrompts: [
      'Summarize the termination clause risks in this vendor agreement.',
      'Highlight non-standard indemnity language that needs counsel review.',
    ],
    certifications: ['GDPR', 'DPDP', 'ISO 42001'],
    usedBy: 189,
    setupMinutes: 20,
  },
  {
    id: '5',
    name: 'Finance Agent',
    type: 'finance',
    industry: 'Banking',
    description: 'Financial services bot for account queries, loan applications, and transaction support.',
    businessPurpose: 'Support finance operations with governed responses, cost visibility, and approvals around sensitive money movement.',
    features: ['Account Queries', 'Loan Applications', 'Transaction Support', 'Fraud Detection', 'Compliance Verification'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 4000,
    price: '₹45,000/month',
    icon: Wallet,
    color: 'amber',
    maturity: 'Core',
    riskLevel: 'High',
    approvalDefault: 'Require approval for payment actions, waivers, and high-risk customer decisions',
    requiredSystems: ['Core finance system', 'Ticketing', 'Compliance records'],
    samplePrompts: [
      'Prepare a summary of failed payout attempts from the last 24 hours.',
      'Draft the analyst notes for this flagged transaction.',
    ],
    certifications: ['RBI', 'SEBI', 'DPDP'],
    usedBy: 276,
    setupMinutes: 15,
  },
  {
    id: '6',
    name: 'IT Support Agent',
    type: 'it_support',
    industry: 'Technology',
    description: 'IT helpdesk agent for ticket creation, troubleshooting, and knowledge base access.',
    features: ['Ticket Creation', 'Troubleshooting Guide', 'Password Reset', 'System Status', 'Knowledge Base'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹22,000/month',
    icon: Server,
    color: 'cyan',
  },
  {
    id: '7',
    name: 'Healthcare Agent',
    type: 'healthcare',
    industry: 'Healthcare',
    description: 'Patient triage assistant for appointment scheduling, symptom assessment, and provider matching.',
    features: ['Appointment Scheduling', 'Symptom Triage', 'Provider Matching', 'Insurance Verification', 'Follow-up Care'],
    model: 'google/gemini-2.0-flash-001',
    platform: 'Google',
    budget: 4500,
    price: '₹55,000/month',
    icon: FlaskConical,
    color: 'emerald',
  },
  {
    id: '8',
    name: 'Refund Agent',
    type: 'refund',
    industry: 'E-commerce',
    description: 'Specialized refund processing agent with fraud detection and approval workflows.',
    features: ['Fraud Detection', 'Refund Approval', 'Policy Enforcement', 'Manual Review Queue', 'Audit Trail'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹30,000/month',
    icon: RefreshCw,
    color: 'orange',
  },
  {
    id: '9',
    name: 'Onboarding Agent',
    type: 'onboarding',
    industry: 'Enterprise',
    description: 'New employee onboarding agent for paperwork, training, and welcome communications.',
    features: ['Document Collection', 'Training Modules', 'Welcome Sequences', 'Progress Tracking', 'Manager Alerts'],
    model: 'anthropic/claude-3-haiku',
    platform: 'Anthropic',
    budget: 1000,
    price: '₹15,000/month',
    icon: UserPlus,
    color: 'teal',
  },
  {
    id: '10',
    name: 'Compliance Agent',
    type: 'compliance',
    industry: 'Finance',
    description: 'Regulatory compliance monitor for KYC/AML, audit trails, and policy enforcement.',
    features: ['KYC Verification', 'AML Screening', 'Audit Trails', 'Policy Enforcement', 'Risk Alerts'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹65,000/month',
    icon: ShieldAlert,
    color: 'rose',
    roi: 'Reduces compliance risk by 95%',
    complexity: 'Advanced',
    certifications: ['RBI', 'SEBI', 'DPDP', 'ISO 42001'],
    usedBy: 163,
    setupMinutes: 20,
  },
  {
    id: '11',
    name: 'Marketing & Content Agent',
    type: 'marketing',
    industry: 'E-commerce',
    description: 'Creative assistant for SEO optimization, social media drafting, and blog post generation.',
    features: ['SEO Optimization', 'Social Media Drafting', 'Blog Post Generation', 'Copy Reviewing', 'Keyword Research'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹35,000/month',
    icon: PenTool,
    color: 'pink',
    roi: 'Boosts content pipeline output by 3x',
    complexity: 'Basic',
  },
  {
    id: '12',
    name: 'Data Analyst Agent',
    type: 'data_analysis',
    industry: 'Enterprise',
    description: 'Analytical engine for SQL querying, data visualization, and predictive modeling.',
    features: ['SQL Querying', 'Data Visualization', 'Report Generation', 'Trend Analysis', 'Predictive Modeling'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 5000,
    price: '₹50,000/month',
    icon: Database,
    color: 'indigo',
    roi: 'Accelerates data reporting to real-time',
    complexity: 'Expert',
  },
  {
    id: '13',
    name: 'Software Developer Agent',
    type: 'engineering',
    industry: 'Technology',
    description: 'Coding assistant for PR reviews, bug detection, and code scaffolding.',
    features: ['PR Reviews', 'Bug Detection', 'Documentation Generation', 'Code Scaffolding', 'Refactoring'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹60,000/month',
    icon: Code,
    color: 'sky',
    roi: 'Increases developer throughput by 40%',
    complexity: 'Expert',
  },
  {
    id: '14',
    name: 'Customer Success Agent',
    type: 'customer_success',
    industry: 'B2B',
    description: 'Post-sales success agent for onboarding customers, tracking renewals, and reducing churn.',
    features: ['Onboarding Playbooks', 'Health Score Summaries', 'Renewal Reminders', 'QBR Prep', 'Escalation Triage'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹28,000/month',
    icon: HeartHandshake,
    color: 'emerald',
    roi: 'Improves retention by 10–20%',
    complexity: 'Basic',
  },
  {
    id: '15',
    name: 'Recruiting Agent',
    type: 'recruiting',
    industry: 'Enterprise',
    description: 'Recruiting assistant for sourcing, screening, interview scheduling, and candidate communications.',
    features: ['Resume Screening', 'Candidate Outreach', 'Interview Scheduling', 'Scorecards', 'ATS Notes Drafting'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹32,000/month',
    icon: UserSearch,
    color: 'purple',
    roi: 'Cuts time-to-screen by 50%',
    complexity: 'Advanced',
  },
  {
    id: '16',
    name: 'Payroll & Benefits Agent',
    type: 'payroll',
    industry: 'Enterprise',
    description: 'Payroll/benefits helpdesk agent for payslip questions, tax forms, and benefits enrollment support.',
    features: ['Payslip Explainers', 'Form Guidance', 'Benefits FAQ', 'Enrollment Nudges', 'Policy Routing'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3500,
    price: '₹40,000/month',
    icon: BadgeDollarSign,
    color: 'amber',
    roi: 'Reduces HR tickets by 30%',
    complexity: 'Basic',
  },
  {
    id: '17',
    name: 'Security Operations Agent',
    type: 'security_ops',
    industry: 'Technology',
    description: 'SOC assistant for triage, alert enrichment, playbook execution, and escalation summaries.',
    features: ['Alert Enrichment', 'Triage Summaries', 'Playbook Checklists', 'Incident Handoff Notes', 'Evidence Collection'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 6500,
    price: '₹70,000/month',
    icon: Shield,
    color: 'rose',
    roi: 'Speeds triage by 2–3x',
    complexity: 'Expert',
  },
  {
    id: '18',
    name: 'DevOps Agent',
    type: 'devops',
    industry: 'Technology',
    description: 'DevOps assistant for incident comms, runbook guidance, CI/CD troubleshooting, and service health checks.',
    features: ['Runbook Guidance', 'Deploy Checklists', 'Log Summaries', 'SLO/SLI Notes', 'Postmortem Drafting'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 4000,
    price: '₹45,000/month',
    icon: Server,
    color: 'cyan',
    roi: 'Reduces MTTR by 20%',
    complexity: 'Advanced',
  },
  {
    id: '19',
    name: 'QA Testing Agent',
    type: 'qa',
    industry: 'Technology',
    description: 'QA assistant for test case generation, bug reproduction steps, and release quality checklists.',
    features: ['Test Case Drafting', 'Bug Triage', 'Repro Steps', 'Release Checklists', 'Acceptance Criteria Review'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹27,000/month',
    icon: Bug,
    color: 'indigo',
    roi: 'Improves regression coverage by 30%',
    complexity: 'Basic',
  },
  {
    id: '20',
    name: 'Procurement Agent',
    type: 'procurement',
    industry: 'Enterprise',
    description: 'Procurement assistant for vendor comparisons, RFQ drafting, approvals, and contract intake.',
    features: ['RFQ Drafting', 'Vendor Comparison', 'Approval Routing', 'Policy Checks', 'Savings Tracking'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹33,000/month',
    icon: ClipboardList,
    color: 'teal',
    roi: 'Improves purchasing cycle time by 25%',
    complexity: 'Advanced',
  },
  {
    id: '21',
    name: 'Logistics Agent',
    type: 'logistics',
    industry: 'E-commerce',
    description: 'Logistics assistant for shipment tracking, carrier updates, delivery exceptions, and customer updates.',
    features: ['Shipment Tracking', 'Delivery Exception Handling', 'Carrier Updates', 'Customer Notifications', 'Return Routing'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2200,
    price: '₹26,000/month',
    icon: Truck,
    color: 'orange',
    roi: 'Reduces "Where is my order?" tickets',
    complexity: 'Basic',
  },
  {
    id: '22',
    name: 'Documentation Agent',
    type: 'documentation',
    industry: 'Technology',
    description: 'Documentation assistant for writing, updating, and validating product docs and internal runbooks.',
    features: ['Docs Drafting', 'Change Summaries', 'Runbook Updates', 'Style Consistency', 'FAQ Generation'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 2500,
    price: '₹30,000/month',
    icon: FileText,
    color: 'sky',
    roi: 'Cuts docs effort by 40%',
    complexity: 'Basic',
  },
  {
    id: '23',
    name: 'Call Center Agent',
    type: 'call_center',
    industry: 'E-commerce',
    description: 'Voice/chat-ready agent for call summaries, next-best actions, and consistent customer responses.',
    features: ['Call Summaries', 'Suggested Replies', 'Disposition Tags', 'Knowledge Base Lookup', 'Escalation Handoff'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹34,000/month',
    icon: PhoneCall,
    color: 'blue',
    roi: 'Improves handle time by 15%',
    complexity: 'Advanced',
  },
  {
    id: '24',
    name: 'Facilities Agent',
    type: 'facilities',
    industry: 'Enterprise',
    description: 'Facilities assistant for service requests, vendor dispatch, maintenance schedules, and workplace FAQs.',
    features: ['Service Requests', 'Vendor Dispatch', 'Maintenance Schedules', 'Access Coordination', 'Workplace FAQ'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹21,000/month',
    icon: Building2,
    color: 'slate',
    roi: 'Improves request resolution speed',
    complexity: 'Basic',
  },
  {
    id: '25',
    name: 'Learning & Development Agent',
    type: 'learning',
    industry: 'Enterprise',
    description: 'L&D assistant for course recommendations, learning paths, quiz generation, and training reminders.',
    features: ['Learning Paths', 'Course Recommendations', 'Quizzes', 'Training Reminders', 'Progress Summaries'],
    model: 'google/gemini-2.0-flash-001',
    platform: 'Google',
    budget: 2000,
    price: '₹24,000/month',
    icon: GraduationCap,
    color: 'purple',
    roi: 'Increases completion rates',
    complexity: 'Basic',
  },
  // ── India-market agents ────────────────────────────────────────────────────
  {
    id: 'india-gst-reconciler',
    name: 'GST Reconciler',
    type: 'finance_gst',
    industry: 'India',
    description: 'Automatically reconciles GSTR-2A with your purchase register, flags mismatches, and prepares filing-ready reports — saving your CA firm hours of manual work.',
    features: ['GSTR-2A vs Purchase Register Matching', 'Mismatch Flagging & Alerts', 'Filing-Ready Report Generation', 'Tally Integration', 'Monthly GST Summary'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹4,999/month',
    icon: Calculator,
    color: 'emerald',
    roi: 'Saves 15+ hours/month on GST reconciliation',
    complexity: 'Advanced',
  },
  {
    id: 'india-whatsapp-lead',
    name: 'WhatsApp Lead Qualifier',
    type: 'sales_lead_whatsapp',
    industry: 'India',
    description: 'Responds to WhatsApp enquiries 24/7, qualifies leads by asking the right questions, and books meetings — in Hindi, English, or Hinglish.',
    features: ['WhatsApp Business API', 'Multilingual (Hindi/English/Hinglish)', 'Lead Scoring & Qualification', 'Auto Meeting Booking', 'CRM Auto-Update'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹3,999/month',
    icon: MessageCircle,
    color: 'green',
    roi: 'Qualifies leads 24/7, books 3x more meetings',
    complexity: 'Basic',
  },
  {
    id: 'india-resume-screener',
    name: 'Resume Screener',
    type: 'hr_recruitment_screening',
    industry: 'India',
    description: 'Screens applications from Naukri, LinkedIn, and email, ranks candidates against your job criteria, and schedules interviews — replacing manual screening.',
    features: ['Multi-Source Intake (Naukri/LinkedIn/Email)', 'AI Candidate Ranking', 'JD Matching & Scoring', 'Auto Interview Scheduling', 'Shortlist Reports'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 2500,
    price: '₹4,499/month',
    icon: UserSearch,
    color: 'purple',
    roi: 'Cuts screening time by 80% — processes 500 resumes/day',
    complexity: 'Advanced',
  },
  {
    id: 'india-payment-followup',
    name: 'Payment Follow-Up Agent',
    type: 'finance_payment_reminder',
    industry: 'India',
    description: 'Sends polite payment reminders via WhatsApp, tracks Cashfree/Tally payment status, and escalates overdue invoices — so you get paid faster.',
    features: ['WhatsApp Payment Reminders', 'Cashfree Status Tracking', 'Tally Invoice Sync', 'Escalation After Due Date', 'Payment Confirmation Alerts'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1500,
    price: '₹2,499/month',
    icon: IndianRupee,
    color: 'amber',
    roi: 'Recovers 25% more overdue payments within 30 days',
    complexity: 'Basic',
  },
  {
    id: 'india-compliance-monitor',
    name: 'DPDP Compliance Monitor',
    type: 'compliance_dpdp',
    industry: 'India',
    description: 'Tracks Digital Personal Data Protection Act deadlines, monitors PII handling across your agents, and generates compliance evidence — keeping you audit-ready.',
    features: ['DPDP Act Compliance Tracking', 'PII Detection (Aadhaar, PAN, UPI)', 'Consent Management Alerts', 'Breach Notification Workflows', 'Audit Evidence Export'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 2000,
    price: '₹3,499/month',
    icon: ShieldCheck,
    color: 'blue',
    roi: 'Stay DPDP-compliant without a dedicated DPO',
    complexity: 'Advanced',
  },
  {
    id: 'india-vendor-onboarding',
    name: 'Vendor Onboarding Agent',
    type: 'procurement_vendor_kyc',
    industry: 'India',
    description: 'Collects vendor KYC documents via WhatsApp (GST certificate, PAN, MSME registration), validates them, and creates vendor records — fully automated.',
    features: ['WhatsApp Document Collection', 'GST Number Validation', 'PAN & MSME Verification', 'Auto Vendor Record Creation', 'Compliance Checklist Tracking'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1500,
    price: '₹2,999/month',
    icon: ClipboardList,
    color: 'teal',
    roi: 'Reduces vendor onboarding from 2 weeks to 2 days',
    complexity: 'Basic',
  },
  {
    id: 'india-site-visit-scheduler',
    name: 'Site Visit Scheduler',
    type: 'sales_real_estate',
    industry: 'India',
    description: 'Handles WhatsApp enquiries for real estate, qualifies buyers by budget and location, schedules site visits, and sends automated reminders.',
    features: ['WhatsApp Lead Intake', 'Budget & Location Qualification', 'Auto Site Visit Scheduling', 'Reminder Notifications', 'Agent Assignment'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1500,
    price: '₹2,999/month',
    icon: Building2,
    color: 'orange',
    roi: 'Books 2x more site visits with zero manual coordination',
    complexity: 'Basic',
  },
  {
    id: 'india-cashfree-reconciler',
    name: 'Cashfree Reconciler',
    type: 'finance_payment_cashfree',
    industry: 'India',
    description: 'Automatically reconciles Cashfree settlements with Tally entries, flags discrepancies, and generates daily payment reports for your finance team.',
    features: ['Cashfree Settlement Matching', 'Tally Auto-Reconciliation', 'Discrepancy Alerts', 'Daily Payment Reports', 'Refund Tracking'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹3,999/month',
    icon: CreditCard,
    color: 'sky',
    roi: 'Eliminates manual payment reconciliation entirely',
    complexity: 'Advanced',
  },
  {
    id: 'india-tally-assistant',
    name: 'Tally Assistant',
    type: 'finance_tally',
    industry: 'India',
    description: 'Answers Tally-related queries via WhatsApp — "Sharma ji ka payment aaya?" gets an instant answer. Checks invoices, balances, and ledger entries on demand.',
    features: ['WhatsApp Query Interface', 'Invoice Status Lookup', 'Ledger Balance Checks', 'Outstanding Reports', 'Hindi/Hinglish Support'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1200,
    price: '₹1,999/month',
    icon: Receipt,
    color: 'rose',
    roi: 'Instant financial answers — no more calling the accountant',
    complexity: 'Basic',
  },
  {
    id: 'india-naukri-tracker',
    name: 'Naukri Application Tracker',
    type: 'hr_recruitment_naukri',
    industry: 'India',
    description: 'Monitors Naukri job postings, tracks incoming applications, auto-screens against job descriptions, and sends shortlist reports to hiring managers daily.',
    features: ['Naukri Integration', 'Auto Application Screening', 'JD Match Scoring', 'Daily Shortlist Reports', 'Hiring Manager Notifications'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹3,499/month',
    icon: ScanSearch,
    color: 'indigo',
    roi: 'Processes 1000+ Naukri applications per day automatically',
    complexity: 'Advanced',
  },
  // ── Custom ─────────────────────────────────────────────────────────────────
  {
    id: 'custom',
    name: 'Create Custom Agent',
    type: 'custom',
    industry: 'All',
    description: 'Build your own specialized AI agent from scratch with custom instructions, tools, and selected models.',
    features: ['Custom System Prompt', 'Any Supported Model', 'Custom Tool Integrations', 'Domain Specific Knowledge', 'Custom Sandbox'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 0,
    price: 'Pay as you go',
    icon: Plus,
    color: 'slate',
    roi: 'Tailored perfectly for your use case',
    complexity: 'Advanced',
  },
];
