import type { IntegrationSpec } from './spec-types';

const API_CALLBACK_BASE = '/api/integrations/oauth/callback';

export const PHASE1_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'naukri',
    name: 'Naukri.com',
    category: 'RECRUITMENT',
    description: "India's largest job portal. Resume matching, candidate scoring, and job posting automation.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'RECRUITMENT', 'AI-READY'],
    status: 'READY',
    color: '#4A90D9',
    priority: 1,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Naukri API Key', required: true, description: 'Partner API key from Naukri' },
        { name: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Enter Client ID', required: true, description: 'Client identifier' },
        { name: 'employer_id', label: 'Employer ID', type: 'text', placeholder: 'Enter Employer ID', required: true, description: 'Your employer account ID' },
      ],
      testEndpoint: 'https://api.naukri.com/v1/jobs?limit=1',
      baseUrl: 'https://api.naukri.com/v1',
    },
    endpoints: {
      jobs: { method: 'GET', path: '/jobs' },
      createJob: { method: 'POST', path: '/jobs' },
      searchCandidates: { method: 'GET', path: '/candidates/search' },
      getCandidate: { method: 'GET', path: '/candidates/{id}' },
      parseResume: { method: 'POST', path: '/candidates/parse' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['resume_matching', 'candidate_scoring', 'skill_extraction'],
      dataTypes: ['resumes', 'job_descriptions', 'candidate_profiles'],
    },
  },
  {
    id: 'cleartax',
    name: 'ClearTax',
    category: 'COMPLIANCE',
    description: "India's tax & compliance platform. TDS calculation, GST filing, and compliance monitoring.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'COMPLIANCE', 'AI-READY'],
    status: 'READY',
    color: '#00A651',
    priority: 1,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter ClearTax API Key', required: true, description: 'From ClearTax developer dashboard' },
        { name: 'gstin', label: 'Company GSTIN', type: 'text', placeholder: '22AAAAA0000A1Z5', required: true, description: 'Company GST number' },
        { name: 'pan', label: 'Company PAN', type: 'text', placeholder: 'AAAAA0000A', required: true, description: 'Company PAN number' },
      ],
      testEndpoint: 'https://api.cleartax.in/v1/compliance/status',
      baseUrl: 'https://api.cleartax.in/v1',
    },
    endpoints: {
      complianceStatus: { method: 'GET', path: '/compliance/status' },
      calculateTDS: { method: 'POST', path: '/tds/calculate' },
      taxRules: { method: 'GET', path: '/tax/rules' },
      gstReturns: { method: 'POST', path: '/gst/returns' },
      notices: { method: 'GET', path: '/notices' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['compliance_monitoring', 'tax_calculation', 'deadline_prediction', 'anomaly_detection'],
      dataTypes: ['tax_rules', 'compliance_status', 'filings'],
    },
  },
  {
    id: 'zoho_people',
    name: 'Zoho People',
    category: 'HRMS',
    description: 'Zoho HRMS. Attrition prediction, workforce analytics, and employee lifecycle telemetry.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'HRMS', 'AI-READY'],
    status: 'READY',
    color: '#D97706',
    priority: 1,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoPeople.modules.ALL', 'ZohoPeople.users.READ', 'ZohoPeople.users.ALL'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_people`,
    },
    endpoints: {
      employees: { method: 'GET', path: '/employees' },
      employee: { method: 'GET', path: '/employees/{id}' },
      attendance: { method: 'GET', path: '/attendance' },
      leave: { method: 'GET', path: '/leave' },
      performance: { method: 'GET', path: '/performance' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['attrition_prediction', 'performance_prediction', 'workforce_analytics', 'anomaly_detection'],
      dataTypes: ['employees', 'attendance', 'leave', 'performance'],
    },
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'RECRUITMENT',
    description: 'Talent intelligence, skill mapping, and professional network analysis.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'RECRUITMENT', 'AI-READY'],
    status: 'READY',
    color: '#0A66C2',
    priority: 1,
    oauthConfig: {
      authorizationUrl: 'https://www.linkedin.com/oauth/v2/authorization',
      tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
      scopes: ['r_liteprofile', 'r_emailaddress', 'r_basicprofile', 'w_member_social'],
      redirectPath: `${API_CALLBACK_BASE}/linkedin`,
    },
    endpoints: {
      profile: { method: 'GET', path: '/me' },
      person: { method: 'GET', path: '/people/{id}' },
      search: { method: 'GET', path: '/people/search' },
      skills: { method: 'GET', path: '/skills' },
      share: { method: 'POST', path: '/shares' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['talent_intelligence', 'skill_mapping', 'network_analysis', 'career_trajectory'],
      dataTypes: ['profiles', 'skills', 'endorsements', 'connections'],
    },
  },
  {
    id: 'tally',
    name: 'Tally.ERP',
    category: 'FINANCE',
    description: "India's most popular accounting software. Expense analytics and HR spend insights.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'FINANCE', 'AI-READY'],
    status: 'READY',
    color: '#2E86AB',
    priority: 1,
    apiKeyConfig: {
      requiredFields: [
        { name: 'company_name', label: 'Company Name', type: 'text', placeholder: 'My Company', required: true, description: 'Tally company name' },
        { name: 'server_url', label: 'Server URL', type: 'text', placeholder: 'http://localhost:9000', required: true, description: 'Tally server URL' },
        { name: 'username', label: 'Username', type: 'text', placeholder: 'Admin', required: false, description: 'Optional username' },
        { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false, description: 'Optional password' },
      ],
      testEndpoint: '/companies',
      baseUrl: '',
    },
    endpoints: {
      companies: { method: 'GET', path: '/companies', format: 'xml' },
      ledgers: { method: 'GET', path: '/ledgers', format: 'xml' },
      vouchers: { method: 'GET', path: '/vouchers', format: 'xml' },
      stockItems: { method: 'GET', path: '/stockitems', format: 'xml' },
      postVoucher: { method: 'POST', path: '/vouchers', format: 'xml' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['expense_analytics', 'budget_prediction', 'anomaly_detection', 'trend_analysis'],
      dataTypes: ['ledgers', 'vouchers', 'transactions'],
    },
    notes: 'Tally uses an XML-style API and is usually reachable only inside the customer network.',
  },
];

export const PHASE2_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'greythr',
    name: 'Greythr',
    category: 'HRMS',
    description: "India's leading HRMS for SMEs. Workforce planning, attendance automation, and payroll telemetry.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'HRMS', 'SME FOCUS', 'AI-READY'],
    status: 'READY',
    color: '#6366F1',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Greythr API Key', required: true, description: 'From Greythr admin settings' },
        { name: 'company_id', label: 'Company ID', type: 'text', placeholder: 'Enter Company ID', required: true, description: 'Company identifier' },
        { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'company.greythr.com', required: true, description: 'Company subdomain' },
      ],
      testEndpoint: 'https://api.greythr.com/v2/employees',
      baseUrl: 'https://api.greythr.com/v2',
    },
    endpoints: {
      employees: { method: 'GET', path: '/employees' },
      employee: { method: 'GET', path: '/employees/{id}' },
      attendance: { method: 'GET', path: '/attendance' },
      leaves: { method: 'GET', path: '/leaves' },
      payroll: { method: 'GET', path: '/payroll' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['workforce_planning', 'attendance_analytics', 'leave_prediction', 'payroll_anomaly'],
      dataTypes: ['employees', 'attendance', 'leaves', 'payroll'],
    },
  },
  {
    id: 'zoho_recruit',
    name: 'Zoho Recruit',
    category: 'ATS',
    description: 'Applicant tracking with resume parsing, pipeline management, and hiring analytics.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'ATS', 'AI-READY'],
    status: 'READY',
    color: '#DC2626',
    priority: 2,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoRecruit.modules.ALL', 'ZohoRecruit.users.READ'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_recruit`,
    },
    endpoints: {
      candidates: { method: 'GET', path: '/Candidates' },
      createCandidate: { method: 'POST', path: '/Candidates' },
      jobOpenings: { method: 'GET', path: '/JobOpenings' },
      createJob: { method: 'POST', path: '/JobOpenings' },
      parseResume: { method: 'POST', path: '/parse/resume' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['resume_parsing', 'candidate_matching', 'pipeline_analytics', 'hiring_prediction'],
      dataTypes: ['candidates', 'jobs', 'applications', 'interviews'],
    },
  },
  {
    id: 'apna',
    name: 'Apna',
    category: 'RECRUITMENT',
    description: "India's largest professional network for blue-collar workers. Mass recruitment telemetry.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'BLUE-COLLAR', 'AI-READY'],
    status: 'READY',
    color: '#F59E0B',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Apna API Key', required: true, description: 'Partner API key from Apna' },
        { name: 'employer_id', label: 'Employer ID', type: 'text', placeholder: 'Enter Employer ID', required: true, description: 'Your employer ID' },
      ],
      testEndpoint: 'https://api.apna.co/v1/jobs',
      baseUrl: 'https://api.apna.co/v1',
    },
    endpoints: {
      jobs: { method: 'GET', path: '/jobs' },
      createJob: { method: 'POST', path: '/jobs' },
      candidates: { method: 'GET', path: '/candidates' },
      candidateProfile: { method: 'GET', path: '/candidates/{id}/profile' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['candidate_matching', 'skill_assessment', 'mass_recruitment', 'availability_prediction'],
      dataTypes: ['candidate_profiles', 'job_preferences', 'applications'],
    },
  },
  {
    id: 'aadhaar',
    name: 'Aadhaar API',
    category: 'IDENTITY',
    description: 'UIDAI Aadhaar authentication and KYC verification. Use a sandbox for testing.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'KYC', 'GOVERNMENT', 'AI-READY'],
    status: 'READY',
    color: '#059669',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'license_key', label: 'License Key', type: 'password', placeholder: 'Enter UIDAI License Key', required: true, description: 'UIDAI license key' },
        { name: 'aua_code', label: 'AUA Code', type: 'text', placeholder: 'Enter AUA Code', required: true, description: 'Authentication User Agency code' },
        { name: 'sub_aua_code', label: 'Sub-AUA Code', type: 'text', placeholder: 'Enter Sub-AUA Code', required: true, description: 'Sub-AUA code' },
      ],
      testEndpoint: 'https://api.uidai.gov.in/v1/status',
      baseUrl: 'https://api.uidai.gov.in/v1',
    },
    endpoints: {
      auth: { method: 'POST', path: '/auth' },
      eKyc: { method: 'POST', path: '/e-kyc' },
      otp: { method: 'POST', path: '/otp' },
      status: { method: 'GET', path: '/status' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['identity_verification', 'face_matching', 'address_verification', 'fraud_detection'],
      dataTypes: ['identity_data', 'demographics', 'photos'],
    },
    notes: 'Requires UIDAI registration and compliance. Use sandbox for testing.',
  },
];

export const PHASE3_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'digilocker',
    name: 'DigiLocker',
    category: 'DOCUMENTS',
    description: 'Government digital locker. Document processing, verification, and AI-ready evidence intake.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'DOCUMENTS', 'GOVERNMENT', 'AI-READY'],
    status: 'READY',
    color: '#0284C7',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://api.digitallocker.gov.in/oauth2/authorize',
      tokenUrl: 'https://api.digitallocker.gov.in/oauth2/token',
      scopes: ['file_fetch', 'file_upload'],
      redirectPath: `${API_CALLBACK_BASE}/digilocker`,
    },
    endpoints: {
      files: { method: 'GET', path: '/files' },
      file: { method: 'GET', path: '/files/{id}' },
      certificates: { method: 'GET', path: '/certificates' },
      verify: { method: 'POST', path: '/verify' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['document_processing', 'certificate_verification', 'ocr', 'fraud_detection'],
      dataTypes: ['documents', 'certificates', 'identity_proofs'],
    },
  },
  {
    id: 'idfy',
    name: 'IDfy',
    category: 'BGV',
    description: 'Background verification. Employment, education, and identity verification automation.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'BGV', 'AI-READY'],
    status: 'READY',
    color: '#7C3AED',
    priority: 3,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter IDfy API Key', required: true, description: 'API key from IDfy dashboard' },
        { name: 'account_id', label: 'Account ID', type: 'text', placeholder: 'Enter Account ID', required: true, description: 'Account identifier' },
      ],
      testEndpoint: 'https://api.idfy.com/v3/status',
      baseUrl: 'https://api.idfy.com/v3',
    },
    endpoints: {
      identityCheck: { method: 'POST', path: '/verification/identity' },
      employmentCheck: { method: 'POST', path: '/verification/employment' },
      educationCheck: { method: 'POST', path: '/verification/education' },
      criminalCheck: { method: 'POST', path: '/verification/criminal' },
      status: { method: 'GET', path: '/verification/{id}/status' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['risk_scoring', 'verification_automation', 'fraud_detection', 'pattern_analysis'],
      dataTypes: ['verification_status', 'risk_scores', 'reports'],
    },
  },
  {
    id: 'zoho_learn',
    name: 'Zoho Learn',
    category: 'LMS',
    description: 'Learning management from Zoho. Skill recommendations, learning paths, and certification tracking.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'LMS', 'AI-READY'],
    status: 'READY',
    color: '#EA580C',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoLearn.modules.ALL', 'ZohoLearn.users.READ'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_learn`,
    },
    endpoints: {
      courses: { method: 'GET', path: '/courses' },
      course: { method: 'GET', path: '/courses/{id}' },
      learners: { method: 'GET', path: '/learners' },
      skills: { method: 'GET', path: '/skills' },
      recommendations: { method: 'POST', path: '/recommendations' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['skill_gap_analysis', 'course_recommendations', 'learning_path', 'certification_tracking'],
      dataTypes: ['courses', 'skills', 'progress', 'certifications'],
    },
  },
  {
    id: 'paytm',
    name: 'Paytm Business',
    category: 'PAYMENTS',
    description: 'Payment gateway in India. Payment analytics, salary disbursement tracking, and payout telemetry.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'PAYMENTS', 'AI-READY'],
    status: 'READY',
    color: '#00B9F5',
    priority: 3,
    apiKeyConfig: {
      requiredFields: [
        { name: 'merchant_id', label: 'Merchant ID', type: 'text', placeholder: 'Enter Merchant ID', required: true, description: 'Paytm merchant ID' },
        { name: 'merchant_key', label: 'Merchant Key', type: 'password', placeholder: 'Enter Merchant Key', required: true, description: 'Merchant key from dashboard' },
        { name: 'channel_id', label: 'Channel ID', type: 'text', placeholder: 'Enter Channel ID', required: true, description: 'Channel identifier' },
      ],
      testEndpoint: 'https://api.paytm.com/v1/merchant/status',
      baseUrl: 'https://api.paytm.com/v1',
    },
    endpoints: {
      createPayment: { method: 'POST', path: '/payments' },
      paymentStatus: { method: 'GET', path: '/payments/{id}' },
      transactions: { method: 'GET', path: '/transactions' },
      payouts: { method: 'POST', path: '/payouts' },
      refunds: { method: 'GET', path: '/refunds' },
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['payment_analytics', 'fraud_detection', 'payout_automation', 'expense_tracking'],
      dataTypes: ['transactions', 'payouts', 'refunds'],
    },
  },
];

export const PHASE4_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    category: 'PRODUCTIVITY',
    description: 'Identity + productivity telemetry across Gmail, Drive, Calendar, and Directory.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'SSO', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#4285F4',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'openid',
        'email',
        'profile',
        'https://www.googleapis.com/auth/calendar',
        'https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/gmail.send',
        'https://www.googleapis.com/auth/admin.directory.user',
      ],
      redirectPath: `${API_CALLBACK_BASE}/google_workspace`,
    },
    endpoints: {
      userinfo: { method: 'GET', path: 'https://www.googleapis.com/oauth2/v3/userinfo' },
    },
  },
  {
    id: 'microsoft_365',
    name: 'Microsoft 365',
    category: 'PRODUCTIVITY',
    description: 'Identity + productivity telemetry across Outlook, OneDrive, Calendar, and Directory (Microsoft Graph).',
    authType: 'oauth2',
    tags: ['ENTERPRISE', 'SSO', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#D83B01',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: [
        'openid',
        'email',
        'profile',
        'offline_access',
        'User.Read',
        'Mail.ReadWrite',
        'Calendars.ReadWrite',
        'Files.ReadWrite.All',
        'Directory.Read.All',
      ],
      redirectPath: `${API_CALLBACK_BASE}/microsoft_365`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://graph.microsoft.com/v1.0/me' },
    },
  },
  {
    id: 'keka',
    name: 'Keka HR',
    category: 'HRMS',
    description: 'HRMS + payroll workflows for India. Server-to-server client credentials authentication.',
    authType: 'client_credentials',
    tags: ['INDIA PRIORITY', 'HRMS'],
    status: 'READY',
    color: '#FF6B35',
    priority: 4,
    connectionFields: [
      { name: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Enter Keka Client ID', required: true, description: 'From Keka developer settings' },
      { name: 'client_secret', label: 'Client Secret', type: 'password', placeholder: '••••••••', required: true, description: 'From Keka developer settings' },
      { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany', required: true, description: 'Keka subdomain (without .keka.com)' },
    ],
    endpoints: {
      token: { method: 'POST', path: 'https://{subdomain}.keka.com/oauth/token' },
      employees: { method: 'GET', path: 'https://{subdomain}.keka.com/api/v1/employees' },
    },
  },
  {
    id: 'razorpayx',
    name: 'RazorpayX Payroll',
    category: 'PAYROLL',
    description: 'Payroll disbursements and payout rails via RazorpayX.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'PAYROLL'],
    status: 'READY',
    color: '#0066FF',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'key_id', label: 'Key ID', type: 'text', placeholder: 'rzp_test_...', required: true, description: 'Razorpay Key ID' },
        { name: 'key_secret', label: 'Key Secret', type: 'password', placeholder: '••••••••', required: true, description: 'Razorpay Key Secret' },
        { name: 'account_id', label: 'Account ID', type: 'text', placeholder: 'acc_...', required: true, description: 'RazorpayX account identifier' },
      ],
      testEndpoint: 'https://api.razorpay.com/v1/fund_accounts',
      baseUrl: 'https://api.razorpay.com/v1',
    },
    endpoints: {
      fundAccounts: { method: 'GET', path: '/fund_accounts' },
    },
  },
  {
    id: 'deel',
    name: 'Deel',
    category: 'GLOBAL_PAYROLL',
    description: 'Global payroll + contractor operations.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'PAYROLL'],
    status: 'READY',
    color: '#15357A',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://auth.deel.com/oauth2/authorize',
      tokenUrl: 'https://auth.deel.com/oauth2/token',
      scopes: ['read:contracts', 'write:contracts', 'read:employees', 'write:employees', 'read:payroll'],
      redirectPath: `${API_CALLBACK_BASE}/deel`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://api.deel.com/rest/v2/profile' },
    },
  },
  {
    id: 'gusto',
    name: 'Gusto',
    category: 'PAYROLL',
    description: 'US payroll + benefits operations.',
    authType: 'oauth2',
    tags: ['US PAYROLL'],
    status: 'READY',
    color: '#E87722',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://api.gusto.com/oauth/authorize',
      tokenUrl: 'https://api.gusto.com/oauth/token',
      scopes: ['employees:read', 'employees:write', 'payroll:read', 'payroll:write', 'benefits:read'],
      redirectPath: `${API_CALLBACK_BASE}/gusto`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://api.gusto.com/v1/me' },
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'COMMUNICATION',
    description: 'Messaging telemetry and alert delivery channel.',
    authType: 'oauth2',
    tags: ['COMMUNICATION', 'GLOBAL'],
    status: 'READY',
    color: '#4A154B',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://slack.com/oauth/v2/authorize',
      tokenUrl: 'https://slack.com/api/oauth.v2.access',
      scopes: [
        'channels:read',
        'channels:manage',
        'chat:write',
        'users:read',
        'users:read.email',
        'team:read',
        'incoming-webhook',
      ],
      redirectPath: `${API_CALLBACK_BASE}/slack`,
    },
    endpoints: {
      authTest: { method: 'POST', path: 'https://slack.com/api/auth.test' },
    },
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'COLLABORATION',
    description: 'Collaboration rail via Microsoft Graph.',
    authType: 'oauth2',
    tags: ['ENTERPRISE', 'COLLABORATION'],
    status: 'READY',
    color: '#6264A7',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: ['offline_access', 'Channel.ReadBasic.All', 'ChannelMessage.Send', 'Team.ReadBasic.All', 'User.Read.All'],
      redirectPath: `${API_CALLBACK_BASE}/teams`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://graph.microsoft.com/v1.0/me' },
    },
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business (Gupshup)',
    category: 'COMMUNICATION',
    description: 'WhatsApp messaging rail for alerts and workflows (via Gupshup).',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'MESSAGING'],
    status: 'READY',
    color: '#25D366',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Gupshup API Key', required: true, description: 'From Gupshup dashboard' },
        { name: 'app_name', label: 'App Name', type: 'text', placeholder: 'your-app', required: true, description: 'Gupshup app name' },
        { name: 'phone_number', label: 'Phone Number', type: 'text', placeholder: '+91...', required: true, description: 'WhatsApp sender number (E.164)' },
      ],
      testEndpoint: 'https://api.gupshup.io/sm/api/v1/app',
      baseUrl: 'https://api.gupshup.io/sm/api/v1',
    },
    endpoints: {
      app: { method: 'GET', path: '/app' },
    },
  },
  {
    id: 'okta',
    name: 'Okta',
    category: 'IAM',
    description: 'Identity governance and directory sync.',
    authType: 'oauth2',
    tags: ['IDENTITY', 'ENTERPRISE'],
    status: 'READY',
    color: '#007DC1',
    priority: 4,
    connectionFields: [
      { name: 'domain', label: 'Okta Domain', type: 'text', placeholder: 'dev-123456.okta.com', required: true, description: 'Your Okta domain (no https://)' },
    ],
    oauthConfig: {
      authorizationUrl: 'https://{domain}/oauth2/v1/authorize',
      tokenUrl: 'https://{domain}/oauth2/v1/token',
      scopes: ['okta.users.read', 'okta.users.manage', 'okta.groups.read', 'okta.groups.manage', 'openid'],
      redirectPath: `${API_CALLBACK_BASE}/okta`,
    },
    endpoints: {
      userinfo: { method: 'GET', path: 'https://{domain}/oauth2/v1/userinfo' },
    },
  },
  {
    id: 'flock',
    name: 'Flock',
    category: 'COMMUNICATION',
    description: 'Indian team messaging platform (Slack alternative).',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'COMMUNICATION'],
    status: 'READY',
    color: '#0BA8E0',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://api.flock.com/oauth/authorize',
      tokenUrl: 'https://api.flock.com/oauth/token',
      scopes: ['chat:read', 'chat:write', 'users:read'],
      redirectPath: `${API_CALLBACK_BASE}/flock`,
    },
    endpoints: {
      users: { method: 'GET', path: 'https://api.flock.com/v1/users.list' },
    },
  },
  {
    id: 'epfo',
    name: 'EPFO',
    category: 'COMPLIANCE',
    description: "Employees' Provident Fund Organization. PF compliance telemetry and filing posture.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'GOVERNMENT', 'COMPLIANCE'],
    status: 'READY',
    color: '#1D4ED8',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'establishment_id', label: 'Establishment ID', type: 'text', placeholder: 'Enter EPF Establishment ID', required: true, description: 'EPFO establishment id' },
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter API Key', required: true, description: 'EPFO API key' },
        { name: 'dsc', label: 'DSC (Digital Signature Certificate)', type: 'password', placeholder: 'Digital Signature', required: true, description: 'Digital signature certificate material' },
      ],
      testEndpoint: 'https://api.epfindia.gov.in/v1/establishment',
      baseUrl: 'https://api.epfindia.gov.in/v1',
    },
    endpoints: {
      establishment: { method: 'GET', path: '/establishment' },
    },
  },
];

export const IMPLEMENTED_INTEGRATIONS: IntegrationSpec[] = [
  ...PHASE1_INTEGRATIONS,
  ...PHASE2_INTEGRATIONS,
  ...PHASE3_INTEGRATIONS,
  ...PHASE4_INTEGRATIONS,
];

export function getIntegrationSpec(id: string) {
  return IMPLEMENTED_INTEGRATIONS.find((spec) => spec.id === id) || null;
}
