import { useNavigate } from 'react-router-dom';
import { Brain, ArrowLeft } from 'lucide-react';

const EFFECTIVE_DATE = '1 April 2025';
const COMPANY = 'Rasi Cyber Solutions Private Limited';
const PRODUCT = 'Zapheit';
const CONTACT_EMAIL = 'privacy@zapheit.com';

export default function PrivacyPage() {
  const navigate = useNavigate();
  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-[#050d1a] text-slate-300">
      {/* Nav */}
      <nav className="border-b border-slate-800 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <button onClick={() => navigate('/')} className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center">
              <Brain className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-white">Zapheit</span>
          </button>
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
          <p className="text-slate-500 text-sm">Effective date: {EFFECTIVE_DATE}</p>
          <p className="text-slate-500 text-sm mt-1">
            This policy applies to the {PRODUCT} platform operated by {COMPANY} and is compliant with India's Digital Personal Data Protection Act 2023 (DPDPA).
          </p>
        </div>

        <div className="space-y-10 text-sm leading-7">

          <section>
            <p>
              At {COMPANY}, we take privacy seriously. This Privacy Policy explains what data we collect, why we collect it, how we use it, and your rights over it. We do not sell your data. Ever.
            </p>
          </section>

          <Section title="1. Who We Are">
            <p>
              {COMPANY} is the data controller for information collected through the {PRODUCT} platform. For questions about this policy, contact us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-cyan-400 hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </Section>

          <Section title="2. What Data We Collect">
            <p className="font-medium text-slate-300 mb-2">Account and organisation data</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>Name and email address (provided at signup)</li>
              <li>Organisation name</li>
              <li>Role within your organisation</li>
              <li>Billing information (handled by our payment processor — we do not store card details)</li>
            </ul>

            <p className="font-medium text-slate-300 mb-2">Usage and platform data</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>Agent configurations, deployment settings, and metadata you create</li>
              <li>Conversation logs and messages routed through the LLM gateway</li>
              <li>Incident records, cost data, audit logs generated by the platform</li>
              <li>Integration credentials (encrypted at rest, never logged in plaintext)</li>
            </ul>

            <p className="font-medium text-slate-300 mb-2">Technical data</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>IP address and browser/device type (for security and fraud prevention)</li>
              <li>Session tokens and authentication logs</li>
              <li>API usage metrics and request timestamps</li>
            </ul>
          </Section>

          <Section title="3. How We Use Your Data">
            <ul className="list-disc pl-5 space-y-2">
              <li><span className="text-slate-300 font-medium">Providing the service</span> — operating the platform, processing API requests, storing your agent and incident data.</li>
              <li><span className="text-slate-300 font-medium">Security</span> — detecting abuse, preventing unauthorised access, and maintaining audit trails.</li>
              <li><span className="text-slate-300 font-medium">Communication</span> — sending transactional emails (invitations, alerts, incident notifications). We do not send marketing emails without your consent.</li>
              <li><span className="text-slate-300 font-medium">Improving the service</span> — analysing aggregated, anonymised usage patterns. We do not use your conversation data or personal data to improve our own models.</li>
              <li><span className="text-slate-300 font-medium">Legal compliance</span> — meeting our obligations under Indian law, including the DPDPA 2023.</li>
            </ul>
          </Section>

          <Section title="4. Data We Do NOT Collect or Use">
            <ul className="list-disc pl-5 space-y-2">
              <li>We do not sell your data to any third party.</li>
              <li>We do not use your conversation data or agent outputs to train AI models.</li>
              <li>We do not collect sensitive personal data (health, biometric, financial account details) unless explicitly required by a feature you enable.</li>
              <li>We do not track your activity across other websites.</li>
            </ul>
          </Section>

          <Section title="5. Data Storage and Security">
            <p>Your data is stored using the following infrastructure:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li><span className="text-slate-300 font-medium">Database</span> — Supabase (PostgreSQL), with row-level security ensuring your data is isolated from other organisations.</li>
              <li><span className="text-slate-300 font-medium">API servers</span> — Google Cloud Platform (Cloud Run, asia-south1 region), with encrypted connections (TLS 1.2+).</li>
              <li><span className="text-slate-300 font-medium">Frontend</span> — Vercel (CDN), with HTTPS enforced.</li>
            </ul>
            <p className="mt-3">
              All data is encrypted in transit and at rest. Integration credentials are stored encrypted. We conduct periodic security reviews and maintain an audit log of all sensitive operations.
            </p>
            <p className="mt-3">
              Data may be stored on servers outside India (US/Singapore region). By using the platform, you consent to this transfer. We ensure adequate safeguards are in place in compliance with the DPDPA.
            </p>
          </Section>

          <Section title="6. Data Sharing">
            <p>We share your data only in the following limited cases:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li><span className="text-slate-300 font-medium">AI providers</span> — when you use the LLM gateway, your prompts are forwarded to the AI provider you select (OpenAI, Anthropic, etc.). Their privacy policies apply to that processing.</li>
              <li><span className="text-slate-300 font-medium">Infrastructure providers</span> — Supabase, Google Cloud Platform, and Vercel process data as part of hosting the service. All are bound by data processing agreements.</li>
              <li><span className="text-slate-300 font-medium">Legal requirements</span> — if required by a court order or applicable law, we may disclose data to authorities. We will notify you where legally permitted.</li>
              <li><span className="text-slate-300 font-medium">Business transfer</span> — in the event of a merger or acquisition, your data may transfer to the new entity, which will be bound by this policy.</li>
            </ul>
          </Section>

          <Section title="7. Your Rights (DPDPA 2023)">
            <p>Under the Digital Personal Data Protection Act 2023, you have the following rights:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li><span className="text-slate-300 font-medium">Right to access</span> — request a copy of the personal data we hold about you.</li>
              <li><span className="text-slate-300 font-medium">Right to correction</span> — request correction of inaccurate or incomplete data.</li>
              <li><span className="text-slate-300 font-medium">Right to erasure</span> — request deletion of your personal data. We will action this within 30 days, except where retention is required by law.</li>
              <li><span className="text-slate-300 font-medium">Right to grievance redressal</span> — raise a complaint with us. We will respond within 72 hours.</li>
              <li><span className="text-slate-300 font-medium">Right to nominate</span> — nominate another person to exercise these rights on your behalf in the event of your death or incapacity.</li>
            </ul>
            <p className="mt-3">
              To exercise any of these rights, email us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-cyan-400 hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </Section>

          <Section title="8. Data Retention">
            <ul className="list-disc pl-5 space-y-2">
              <li>Account data is retained for the duration of your subscription plus 90 days after termination.</li>
              <li>Conversation logs and incident data are retained for 12 months by default. You can delete them earlier from within the platform.</li>
              <li>Audit logs are retained for 24 months for compliance purposes.</li>
              <li>Backup copies may be retained for up to 30 additional days.</li>
            </ul>
          </Section>

          <Section title="9. Cookies">
            <p>
              We use only essential cookies required to keep you signed in and maintain your session. We do not use advertising cookies, tracking pixels, or third-party analytics cookies.
            </p>
          </Section>

          <Section title="10. Children's Privacy">
            <p>
              {PRODUCT} is not intended for individuals under 18. We do not knowingly collect data from anyone under 18. If you believe a minor has created an account, contact us and we will delete it promptly.
            </p>
          </Section>

          <Section title="11. Changes to This Policy">
            <p>
              We may update this Privacy Policy from time to time. We will notify you of material changes via email at least 14 days before they take effect. The effective date at the top of this page reflects the latest revision.
            </p>
          </Section>

          <Section title="12. Contact and Grievance Officer">
            <p>
              For privacy questions, data requests, or grievances under the DPDPA, contact our Privacy Officer:
            </p>
            <div className="mt-3 p-4 rounded-xl border border-slate-700 bg-white/[0.02] space-y-1">
              <p className="text-slate-300 font-medium">{COMPANY}</p>
              <p>PH-II GR FL, BL-B 20, Round Tank Ln, Howrah, West Bengal 711101, India</p>
              <p>Mobile: +91-9433116259</p>
              <p>Email: <a href={`mailto:${CONTACT_EMAIL}`} className="text-cyan-400 hover:underline">{CONTACT_EMAIL}</a></p>
              <p className="text-slate-500 text-xs mt-2">We aim to respond to all privacy requests within 72 hours.</p>
            </div>
          </Section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-8 px-6 mt-16">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-slate-500">
          <p>© {year} {COMPANY}. All rights reserved.</p>
          <div className="flex gap-6">
            <button onClick={() => navigate('/terms')} className="hover:text-cyan-400 transition-colors">Terms</button>
            <button onClick={() => navigate('/privacy')} className="hover:text-cyan-400 transition-colors">Privacy</button>
            <button onClick={() => navigate('/')} className="hover:text-cyan-400 transition-colors">Home</button>
          </div>
        </div>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-semibold text-white mb-3">{title}</h2>
      <div className="text-slate-400">{children}</div>
    </section>
  );
}
