// ---------------------------------------------------------------------------
// Synthesized Rules API
// Exposes proposed action policies generated by the Seniority Engine's
// rule-synthesis process (3+ repeated human denials of the same action).
// ---------------------------------------------------------------------------

import { Router, type Request, type Response } from 'express';
import { requirePermission } from '../middleware/rbac';
import { supabaseRestAsUser, supabaseRest, eq } from '../lib/supabase-rest';
import { getOrgId, getUserJwt, errorResponse } from '../lib/route-helpers';
import { logger } from '../lib/logger';

const router = Router();

// GET /api/rules/synthesized — list proposed synthesized rules for the org
router.get('/synthesized', requirePermission('policies.manage'), async (req: Request, res: Response) => {
  try {
    const orgId = getOrgId(req);
    if (!orgId) return res.status(400).json({ success: false, error: 'Organization not found' });

    const status = typeof req.query.status === 'string' ? req.query.status : 'proposed';
    const q = new URLSearchParams();
    q.set('organization_id', eq(orgId));
    q.set('status', eq(status));
    q.set('order', 'created_at.desc');
    q.set('limit', '50');

    const rows = (await supabaseRestAsUser(getUserJwt(req), 'synthesized_rules', q)) as any[];
    return res.json({ success: true, data: rows || [] });
  } catch (err: any) {
    return errorResponse(res, err);
  }
});

// PATCH /api/rules/synthesized/:id — accept or dismiss a proposed rule
router.patch('/synthesized/:id', requirePermission('policies.manage'), async (req: Request, res: Response) => {
  try {
    const orgId = getOrgId(req);
    if (!orgId) return res.status(400).json({ success: false, error: 'Organization not found' });

    const { id } = req.params;
    const { status } = req.body as { status: string };

    if (status !== 'accepted' && status !== 'dismissed') {
      return res.status(400).json({ success: false, error: 'status must be "accepted" or "dismissed"' });
    }

    // Fetch the rule to get proposed_policy
    const q = new URLSearchParams();
    q.set('id', eq(id));
    q.set('organization_id', eq(orgId));
    q.set('limit', '1');
    const rows = (await supabaseRestAsUser(getUserJwt(req), 'synthesized_rules', q)) as any[];
    const rule = rows?.[0];
    if (!rule) return res.status(404).json({ success: false, error: 'Synthesized rule not found' });

    // Update status
    const patchQ = new URLSearchParams();
    patchQ.set('id', eq(id));
    patchQ.set('organization_id', eq(orgId));
    await supabaseRestAsUser(getUserJwt(req), 'synthesized_rules', patchQ, {
      method: 'PATCH',
      body: { status, updated_at: new Date().toISOString() },
    });

    // If accepted, auto-create the action policy (upsert)
    if (status === 'accepted' && rule.proposed_policy) {
      const policy = rule.proposed_policy as Record<string, any>;
      try {
        await supabaseRest('action_policies', '', {
          method: 'POST',
          headers: { Prefer: 'resolution=merge-duplicates,return=minimal' },
          body: {
            organization_id: orgId,
            service: rule.service,
            action: rule.action,
            enabled: true,
            require_approval: policy.require_approval ?? true,
            required_role: policy.required_role ?? 'admin',
            notes: policy.notes ?? `Auto-created from synthesized rule after ${rule.trigger_count} denials.`,
            updated_at: new Date().toISOString(),
          },
        });
        logger.info('[rules] Action policy auto-created from synthesized rule', { orgId, service: rule.service, action: rule.action });
      } catch (err: any) {
        logger.warn('[rules] Failed to auto-create action policy from synthesized rule', { id, error: err?.message });
      }
    }

    return res.json({ success: true, data: { id, status } });
  } catch (err: any) {
    return errorResponse(res, err);
  }
});

export default router;
