import type { IntegrationSpec } from './spec-types';

const API_CALLBACK_BASE = '/api/integrations/oauth/callback';

const INTERNAL_INTEGRATION: IntegrationSpec = {
  id: 'internal',
  name: 'Zapheit (Built-in)',
  category: 'OTHER',
  description: 'Built-in work items and safe actions inside Zapheit. No external credentials required.',
  // Kept as api_key for compatibility; UI/API special-case this to show as connected without configuration.
  authType: 'api_key',
  tags: ['BUILTIN', 'INTERNAL'],
  status: 'READY',
  color: '#64748B',
  priority: 0,
  endpoints: {},
  capabilities: {
    reads: [],
    writes: [
      { id: 'support.ticket.create', label: 'Create support ticket (internal)', risk: 'medium', pack: 'support' },
      { id: 'support.ticket.update_status', label: 'Update ticket status (internal)', risk: 'low', pack: 'support' },
      { id: 'sales.lead.create', label: 'Create sales lead (internal)', risk: 'medium', pack: 'sales' },
      { id: 'sales.lead.update_stage', label: 'Update lead stage (internal)', risk: 'low', pack: 'sales' },
      { id: 'it.access_request.create', label: 'Create access request (internal)', risk: 'high', pack: 'it' },
      { id: 'it.access_request.decide', label: 'Approve/deny access request (internal)', risk: 'high', pack: 'it' },
    ],
  },
  notes: 'These actions create records inside Zapheit and run through Jobs & Approvals via connector_action.',
};

export const PHASE1_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'naukri',
    name: 'Naukri.com',
    category: 'RECRUITMENT',
    description: "India's largest job portal. Resume matching, candidate scoring, and job posting automation.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'RECRUITMENT', 'AI-READY'],
    status: 'READY',
    color: '#4A90D9',
    priority: 1,
    maturity: 'governed',
    trustTier: 'controlled-write',
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Naukri API Key', required: true, description: 'Partner API key from Naukri' },
        { name: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Enter Client ID', required: true, description: 'Client identifier' },
        { name: 'employer_id', label: 'Employer ID', type: 'text', placeholder: 'Enter Employer ID', required: true, description: 'Your employer account ID' },
      ],
      testEndpoint: 'https://api.naukri.com/v1/jobs?limit=1',
      baseUrl: 'https://api.naukri.com/v1',
    },
    endpoints: {
      jobs: { method: 'GET', path: '/jobs' },
      createJob: { method: 'POST', path: '/jobs' },
      searchCandidates: { method: 'GET', path: '/candidates/search' },
      getCandidate: { method: 'GET', path: '/candidates/{id}' },
      parseResume: { method: 'POST', path: '/candidates/parse' },
    },
    capabilities: {
      reads: ['candidate_profiles', 'job_descriptions'],
      writes: [
        {
          id: 'recruitment.candidate.search',
          label: 'Search candidates',
          risk: 'low',
          pack: 'recruitment',
          operation: 'read',
          objectType: 'candidate',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Capture search context for shortlist evidence'],
        },
        {
          id: 'recruitment.resume.parse',
          label: 'Parse candidate resume',
          risk: 'medium',
          pack: 'recruitment',
          operation: 'execute',
          objectType: 'candidate',
          reversible: false,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'request-result',
          constraints: ['Store parsing rationale for recruiting review'],
        },
        {
          id: 'recruitment.job.publish',
          label: 'Publish job opening',
          risk: 'high',
          pack: 'recruitment',
          operation: 'create',
          objectType: 'job',
          reversible: false,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require recruiter or admin approval before job goes live'],
        },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['resume_matching', 'candidate_scoring', 'skill_extraction'],
      dataTypes: ['resumes', 'job_descriptions', 'candidate_profiles'],
    },
  },
  {
    id: 'cleartax',
    name: 'ClearTax',
    category: 'COMPLIANCE',
    description: "India's tax & compliance platform. TDS calculation, GST filing, and compliance monitoring.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'COMPLIANCE', 'AI-READY'],
    status: 'READY',
    color: '#00A651',
    priority: 1,
    maturity: 'governed',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter ClearTax API Key', required: true, description: 'From ClearTax developer dashboard' },
        { name: 'gstin', label: 'Company GSTIN', type: 'text', placeholder: '22AAAAA0000A1Z5', required: true, description: 'Company GST number' },
        { name: 'pan', label: 'Company PAN', type: 'text', placeholder: 'AAAAA0000A', required: true, description: 'Company PAN number' },
      ],
      testEndpoint: 'https://api.cleartax.in/v1/compliance/status',
      baseUrl: 'https://api.cleartax.in/v1',
    },
    endpoints: {
      complianceStatus: { method: 'GET', path: '/compliance/status' },
      calculateTDS: { method: 'POST', path: '/tds/calculate' },
      taxRules: { method: 'GET', path: '/tax/rules' },
      gstReturns: { method: 'POST', path: '/gst/returns' },
      notices: { method: 'GET', path: '/notices' },
    },
    capabilities: {
      reads: ['compliance.tax_rules', 'compliance.status', 'compliance.notices'],
      writes: [
        {
          id: 'compliance.status.check',
          label: 'Check compliance posture',
          risk: 'low',
          pack: 'compliance',
          operation: 'read',
          objectType: 'filing',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Attach compliance snapshot to investigations'],
        },
        {
          id: 'compliance.notice.read',
          label: 'Read tax notices',
          risk: 'medium',
          pack: 'compliance',
          operation: 'read',
          objectType: 'notice',
          reversible: false,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'request-result',
          constraints: ['Record notice access in audit trail'],
        },
        {
          id: 'compliance.gst.file',
          label: 'File GST return',
          risk: 'high',
          pack: 'compliance',
          operation: 'execute',
          objectType: 'filing',
          reversible: false,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require dual approval and submission evidence export'],
        },
        {
          id: 'compliance.tds.calculate',
          label: 'Calculate TDS',
          risk: 'medium',
          pack: 'compliance',
          operation: 'execute',
          objectType: 'filing',
          reversible: true,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'request-result',
          constraints: ['Persist calculation inputs and generated summary'],
        },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['compliance_monitoring', 'tax_calculation', 'deadline_prediction', 'anomaly_detection'],
      dataTypes: ['tax_rules', 'compliance_status', 'filings'],
    },
  },
  {
    id: 'zoho_people',
    name: 'Zoho People',
    category: 'HRMS',
    description: 'Zoho HRMS. Attrition prediction, workforce analytics, and employee lifecycle telemetry.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'HRMS', 'AI-READY'],
    status: 'READY',
    color: '#D97706',
    priority: 1,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoPeople.employee.ALL', 'ZohoPeople.forms.READ'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_people`,
    },
    endpoints: {
      employees: { method: 'GET', path: '/employees' },
      employee: { method: 'GET', path: '/employees/{id}' },
      attendance: { method: 'GET', path: '/attendance' },
      leave: { method: 'GET', path: '/leave' },
      performance: { method: 'GET', path: '/performance' },
    },
    capabilities: {
      reads: ['hr.employees', 'hr.attendance', 'hr.leaves', 'hr.performance'],
      writes: [
        { id: 'hr.employee.update', label: 'Update employee record', risk: 'medium' },
        { id: 'hr.leave.approve', label: 'Approve leave request', risk: 'medium' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['attrition_prediction', 'performance_prediction', 'workforce_analytics', 'anomaly_detection'],
      dataTypes: ['employees', 'attendance', 'leave', 'performance'],
    },
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'RECRUITMENT',
    description: 'Verify candidate profiles and pull basic professional data via LinkedIn OAuth. Full recruiter features (InMail, search, job posting) require LinkedIn Talent Solutions partner access.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'RECRUITMENT', 'AI-READY'],
    status: 'READY',
    color: '#0A66C2',
    priority: 1,
    oauthConfig: {
      authorizationUrl: 'https://www.linkedin.com/oauth/v2/authorization',
      tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
      scopes: ['openid', 'profile', 'email'],
      redirectPath: `${API_CALLBACK_BASE}/linkedin`,
    },
    endpoints: {
      profile: { method: 'GET', path: '/me' },
      person: { method: 'GET', path: '/people/{id}' },
      search: { method: 'GET', path: '/people/search' },
      skills: { method: 'GET', path: '/skills' },
      share: { method: 'POST', path: '/shares' },
    },
    capabilities: {
      reads: ['candidate_profiles_lite'],
      writes: [],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['talent_intelligence', 'skill_mapping', 'network_analysis', 'career_trajectory'],
      dataTypes: ['profiles', 'skills', 'endorsements', 'connections'],
    },
  },
  {
    id: 'tally',
    name: 'Tally.ERP',
    category: 'FINANCE',
    description: "India's most popular accounting software. Expense analytics and HR spend insights.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'FINANCE', 'AI-READY'],
    status: 'READY',
    color: '#2E86AB',
    priority: 1,
    maturity: 'governed',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'company_name', label: 'Company Name', type: 'text', placeholder: 'My Company', required: true, description: 'Tally company name' },
        { name: 'server_url', label: 'Server URL', type: 'text', placeholder: 'http://localhost:9000', required: true, description: 'Tally server URL' },
        { name: 'username', label: 'Username', type: 'text', placeholder: 'Admin', required: false, description: 'Optional username' },
        { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: false, description: 'Optional password' },
      ],
      testEndpoint: '/companies',
      baseUrl: '',
    },
    endpoints: {
      companies: { method: 'GET', path: '/companies', format: 'xml' },
      ledgers: { method: 'GET', path: '/ledgers', format: 'xml' },
      vouchers: { method: 'GET', path: '/vouchers', format: 'xml' },
      stockItems: { method: 'GET', path: '/stockitems', format: 'xml' },
      postVoucher: { method: 'POST', path: '/vouchers', format: 'xml' },
    },
    capabilities: {
      reads: ['finance.ledgers', 'finance.vouchers', 'finance.transactions'],
      writes: [
        {
          id: 'finance.ledger.read',
          label: 'Read ledger summary',
          risk: 'low',
          pack: 'finance',
          operation: 'read',
          objectType: 'ledger',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Preserve ledger query context for reconciliation'],
        },
        {
          id: 'finance.voucher.reconcile',
          label: 'Reconcile vouchers',
          risk: 'medium',
          pack: 'finance',
          operation: 'reconcile',
          objectType: 'voucher',
          reversible: true,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'before-after',
          constraints: ['Store reconciliation diff and reviewer notes'],
        },
        {
          id: 'finance.voucher.post',
          label: 'Post voucher / journal entry',
          risk: 'money',
          pack: 'finance',
          operation: 'create',
          objectType: 'voucher',
          reversible: false,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require threshold policy and sanitized before/after voucher evidence'],
        },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['expense_analytics', 'budget_prediction', 'anomaly_detection', 'trend_analysis'],
      dataTypes: ['ledgers', 'vouchers', 'transactions'],
    },
    notes: 'Tally uses an XML-style API and is usually reachable only inside the customer network.',
  },
];

export const PHASE2_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'greythr',
    name: 'Greythr',
    category: 'HRMS',
    description: "India's leading HRMS for SMEs. Workforce planning, attendance automation, and payroll telemetry.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'HRMS', 'SME FOCUS', 'AI-READY'],
    status: 'READY',
    color: '#6366F1',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Greythr API Key', required: true, description: 'From Greythr admin settings' },
        { name: 'company_id', label: 'Company ID', type: 'text', placeholder: 'Enter Company ID', required: true, description: 'Company identifier' },
        { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'company.greythr.com', required: true, description: 'Company subdomain' },
      ],
      testEndpoint: 'https://api.greythr.com/v2/employees',
      baseUrl: 'https://api.greythr.com/v2',
    },
    endpoints: {
      employees: { method: 'GET', path: '/employees' },
      employee: { method: 'GET', path: '/employees/{id}' },
      attendance: { method: 'GET', path: '/attendance' },
      leaves: { method: 'GET', path: '/leaves' },
      payroll: { method: 'GET', path: '/payroll' },
    },
    capabilities: {
      reads: ['hr.employees', 'hr.attendance', 'hr.leaves', 'hr.payroll'],
      writes: [
        { id: 'hr.leave.approve', label: 'Approve leave request', risk: 'medium' },
        { id: 'hr.attendance.update', label: 'Update attendance record', risk: 'low' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['workforce_planning', 'attendance_analytics', 'leave_prediction', 'payroll_anomaly'],
      dataTypes: ['employees', 'attendance', 'leaves', 'payroll'],
    },
  },
  {
    id: 'zoho_recruit',
    name: 'Zoho Recruit',
    category: 'ATS',
    description: 'Applicant tracking with resume parsing, pipeline management, and hiring analytics.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'ATS', 'AI-READY'],
    status: 'READY',
    color: '#DC2626',
    priority: 2,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoRecruit.modules.ALL', 'offline_access'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_recruit`,
    },
    endpoints: {
      candidates: { method: 'GET', path: '/Candidates' },
      createCandidate: { method: 'POST', path: '/Candidates' },
      jobOpenings: { method: 'GET', path: '/JobOpenings' },
      createJob: { method: 'POST', path: '/JobOpenings' },
      parseResume: { method: 'POST', path: '/parse/resume' },
    },
    capabilities: {
      reads: ['recruitment.candidates', 'recruitment.jobs', 'recruitment.applications'],
      writes: [
        { id: 'recruitment.candidate.create', label: 'Create candidate record', risk: 'low' },
        { id: 'recruitment.job.create', label: 'Create job opening', risk: 'medium' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['resume_parsing', 'candidate_matching', 'pipeline_analytics', 'hiring_prediction'],
      dataTypes: ['candidates', 'jobs', 'applications', 'interviews'],
    },
  },
  {
    id: 'apna',
    name: 'Apna',
    category: 'RECRUITMENT',
    description: "India's largest professional network for blue-collar workers. Mass recruitment telemetry.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'BLUE-COLLAR', 'AI-READY'],
    status: 'READY',
    color: '#F59E0B',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter Apna API Key', required: true, description: 'Partner API key from Apna' },
        { name: 'employer_id', label: 'Employer ID', type: 'text', placeholder: 'Enter Employer ID', required: true, description: 'Your employer ID' },
      ],
      testEndpoint: 'https://api.apna.co/v1/jobs',
      baseUrl: 'https://api.apna.co/v1',
    },
    endpoints: {
      jobs: { method: 'GET', path: '/jobs' },
      createJob: { method: 'POST', path: '/jobs' },
      candidates: { method: 'GET', path: '/candidates' },
      candidateProfile: { method: 'GET', path: '/candidates/{id}/profile' },
    },
    capabilities: {
      reads: ['recruitment.candidates', 'recruitment.jobs'],
      writes: [],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['candidate_matching', 'skill_assessment', 'mass_recruitment', 'availability_prediction'],
      dataTypes: ['candidate_profiles', 'job_preferences', 'applications'],
    },
  },
  {
    id: 'aadhaar',
    name: 'Aadhaar API',
    category: 'IDENTITY',
    description: 'UIDAI Aadhaar authentication and KYC verification. Use a sandbox for testing.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'KYC', 'GOVERNMENT', 'AI-READY'],
    status: 'COMING_SOON',
    color: '#059669',
    priority: 2,
    apiKeyConfig: {
      requiredFields: [
        { name: 'license_key', label: 'License Key', type: 'password', placeholder: 'Enter UIDAI License Key', required: true, description: 'UIDAI license key' },
        { name: 'aua_code', label: 'AUA Code', type: 'text', placeholder: 'Enter AUA Code', required: true, description: 'Authentication User Agency code' },
        { name: 'sub_aua_code', label: 'Sub-AUA Code', type: 'text', placeholder: 'Enter Sub-AUA Code', required: true, description: 'Sub-AUA code' },
      ],
      testEndpoint: 'https://api.uidai.gov.in/v1/status',
      baseUrl: 'https://api.uidai.gov.in/v1',
    },
    endpoints: {
      auth: { method: 'POST', path: '/auth' },
      eKyc: { method: 'POST', path: '/e-kyc' },
      otp: { method: 'POST', path: '/otp' },
      status: { method: 'GET', path: '/status' },
    },
    capabilities: {
      reads: ['identity.kyc'],
      writes: [
        { id: 'identity.kyc.verify', label: 'Verify Aadhaar (eKYC)', risk: 'high' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['identity_verification', 'face_matching', 'address_verification', 'fraud_detection'],
      dataTypes: ['identity_data', 'demographics', 'photos'],
    },
    notes: 'Requires UIDAI registration and compliance. Use sandbox for testing.',
  },
];

export const PHASE3_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'digilocker',
    name: 'DigiLocker',
    category: 'DOCUMENTS',
    description: 'Government digital locker. Document processing, verification, and AI-ready evidence intake.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'DOCUMENTS', 'GOVERNMENT', 'AI-READY'],
    status: 'COMING_SOON',
    color: '#0284C7',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://api.digitallocker.gov.in/oauth2/authorize',
      tokenUrl: 'https://api.digitallocker.gov.in/oauth2/token',
      scopes: ['file_fetch', 'file_upload'],
      redirectPath: `${API_CALLBACK_BASE}/digilocker`,
    },
    endpoints: {
      files: { method: 'GET', path: '/files' },
      file: { method: 'GET', path: '/files/{id}' },
      certificates: { method: 'GET', path: '/certificates' },
      verify: { method: 'POST', path: '/verify' },
    },
    capabilities: {
      reads: ['documents.files', 'documents.certificates'],
      writes: [
        { id: 'documents.certificate.verify', label: 'Verify certificate', risk: 'medium' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['document_processing', 'certificate_verification', 'ocr', 'fraud_detection'],
      dataTypes: ['documents', 'certificates', 'identity_proofs'],
    },
  },
  {
    id: 'idfy',
    name: 'IDfy',
    category: 'BGV',
    description: 'Background verification. Employment, education, and identity verification automation.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'BGV', 'AI-READY'],
    status: 'READY',
    color: '#7C3AED',
    priority: 3,
    apiKeyConfig: {
      requiredFields: [
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter IDfy API Key', required: true, description: 'API key from IDfy dashboard' },
        { name: 'account_id', label: 'Account ID', type: 'text', placeholder: 'Enter Account ID', required: true, description: 'Account identifier' },
      ],
      testEndpoint: 'https://api.idfy.com/v3/status',
      baseUrl: 'https://api.idfy.com/v3',
    },
    endpoints: {
      identityCheck: { method: 'POST', path: '/verification/identity' },
      employmentCheck: { method: 'POST', path: '/verification/employment' },
      educationCheck: { method: 'POST', path: '/verification/education' },
      criminalCheck: { method: 'POST', path: '/verification/criminal' },
      status: { method: 'GET', path: '/verification/{id}/status' },
    },
    capabilities: {
      reads: ['hr.bgv_status'],
      writes: [
        { id: 'hr.bgv.initiate', label: 'Initiate background verification', risk: 'high' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['risk_scoring', 'verification_automation', 'fraud_detection', 'pattern_analysis'],
      dataTypes: ['verification_status', 'risk_scores', 'reports'],
    },
  },
  {
    id: 'zoho_learn',
    name: 'Zoho Learn',
    category: 'LMS',
    description: 'Learning management from Zoho. Skill recommendations, learning paths, and certification tracking.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'LMS', 'AI-READY'],
    status: 'READY',
    color: '#EA580C',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoLearn.course.READ', 'ZohoLearn.course.ALL', 'offline_access'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_learn`,
    },
    endpoints: {
      courses: { method: 'GET', path: '/courses' },
      course: { method: 'GET', path: '/courses/{id}' },
      learners: { method: 'GET', path: '/learners' },
      skills: { method: 'GET', path: '/skills' },
      recommendations: { method: 'POST', path: '/recommendations' },
    },
    capabilities: {
      reads: ['lms.courses', 'lms.learner_progress', 'lms.skills'],
      writes: [
        { id: 'lms.course.assign', label: 'Assign course to employee', risk: 'low' },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['skill_gap_analysis', 'course_recommendations', 'learning_path', 'certification_tracking'],
      dataTypes: ['courses', 'skills', 'progress', 'certifications'],
    },
  },
  {
    id: 'paytm',
    name: 'Paytm Business',
    category: 'PAYMENTS',
    description: 'Payment gateway in India. Payment analytics, salary disbursement tracking, and payout telemetry.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'PAYMENTS', 'AI-READY'],
    status: 'READY',
    color: '#00B9F5',
    priority: 3,
    maturity: 'governed',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'merchant_id', label: 'Merchant ID', type: 'text', placeholder: 'Enter Merchant ID', required: true, description: 'Paytm merchant ID' },
        { name: 'merchant_key', label: 'Merchant Key', type: 'password', placeholder: 'Enter Merchant Key', required: true, description: 'Merchant key from dashboard' },
        { name: 'channel_id', label: 'Channel ID', type: 'text', placeholder: 'Enter Channel ID', required: true, description: 'Channel identifier' },
      ],
      testEndpoint: 'https://api.paytm.com/v1/merchant/status',
      baseUrl: 'https://api.paytm.com/v1',
    },
    endpoints: {
      createPayment: { method: 'POST', path: '/payments' },
      paymentStatus: { method: 'GET', path: '/payments/{id}' },
      transactions: { method: 'GET', path: '/transactions' },
      payouts: { method: 'POST', path: '/payouts' },
      refunds: { method: 'GET', path: '/refunds' },
    },
    capabilities: {
      reads: ['finance.transactions', 'finance.refunds', 'finance.payouts'],
      writes: [
        {
          id: 'finance.payment.status',
          label: 'Check payment status',
          risk: 'low',
          pack: 'finance',
          operation: 'read',
          objectType: 'payment',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Attach payment snapshot to incident and refund evidence'],
        },
        {
          id: 'finance.refund.create',
          label: 'Create refund',
          risk: 'money',
          pack: 'finance',
          operation: 'create',
          objectType: 'refund',
          reversible: true,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require amount threshold policy and refund rationale capture'],
        },
        {
          id: 'finance.payout.initiate',
          label: 'Initiate payout',
          risk: 'money',
          pack: 'finance',
          operation: 'execute',
          objectType: 'payout',
          reversible: false,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require dual approval for beneficiary changes or large disbursements'],
        },
      ],
    },
    aiFeatures: {
      enabled: true,
      capabilities: ['payment_analytics', 'fraud_detection', 'payout_automation', 'expense_tracking'],
      dataTypes: ['transactions', 'payouts', 'refunds'],
    },
  },
];

export const PHASE4_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'DEVOPS',
    description: 'GitHub OAuth integration. Read and manage repos, issues, pull requests, and CI/CD workflows.',
    authType: 'oauth2',
    tags: ['DEVOPS', 'AI-READY'],
    status: 'READY',
    color: '#24292e',
    priority: 2,
    oauthConfig: {
      authorizationUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      scopes: ['repo', 'read:user', 'read:org'],
      redirectPath: `${API_CALLBACK_BASE}/github`,
    },
    endpoints: {
      repos: { method: 'GET', path: '/user/repos' },
      issues: { method: 'GET', path: '/repos/{owner}/{repo}/issues' },
      pulls: { method: 'GET', path: '/repos/{owner}/{repo}/pulls' },
    },
    capabilities: {
      reads: ['devops.repos', 'devops.issues', 'devops.pull_requests'],
      writes: [
        { id: 'devops.issue.create', label: 'Create issue', risk: 'medium' },
        { id: 'devops.issue.comment', label: 'Add comment to issue', risk: 'low' },
        { id: 'devops.pr.merge', label: 'Merge pull request', risk: 'high' },
      ],
    },
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'SUPPORT',
    description: 'Customer support ticketing (read tickets, draft replies, and triage workflows).',
    authType: 'api_key',
    tags: ['SUPPORT', 'GLOBAL'],
    status: 'READY',
    color: '#03363D',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany', required: true, description: 'Zendesk subdomain (yourcompany.zendesk.com)' },
        { name: 'email', label: 'Email', type: 'text', placeholder: 'agent@company.com', required: true, description: 'Agent/admin email' },
        { name: 'api_token', label: 'API Token', type: 'password', placeholder: '••••••••', required: true, description: 'Zendesk API token' },
      ],
      testEndpoint: '/api/v2/users/me.json',
      baseUrl: 'https://{subdomain}.zendesk.com',
    },
    endpoints: {
      me: { method: 'GET', path: 'https://{subdomain}.zendesk.com/api/v2/users/me.json' },
      tickets: { method: 'GET', path: 'https://{subdomain}.zendesk.com/api/v2/tickets.json' },
    },
    capabilities: {
      reads: ['support.tickets'],
      writes: [
        { id: 'support.ticket.reply', label: 'Reply to ticket', risk: 'medium' },
        { id: 'support.ticket.update_status', label: 'Update ticket status', risk: 'low' },
      ],
    },
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    category: 'SUPPORT',
    description: 'Freshdesk ticketing (triage, replies, and SLA workflows).',
    authType: 'api_key',
    tags: ['SUPPORT', 'GLOBAL'],
    status: 'READY',
    color: '#25A7DF',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'domain', label: 'Domain', type: 'text', placeholder: 'yourcompany', required: true, description: 'Freshdesk domain (yourcompany.freshdesk.com)' },
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: '••••••••', required: true, description: 'Freshdesk API key' },
      ],
      testEndpoint: '/api/v2/agents/me',
      baseUrl: 'https://{domain}.freshdesk.com',
    },
    endpoints: {
      me: { method: 'GET', path: 'https://{domain}.freshdesk.com/api/v2/agents/me' },
    },
    capabilities: {
      reads: ['support.tickets'],
      writes: [
        { id: 'support.ticket.reply', label: 'Reply to ticket', risk: 'medium' },
        { id: 'support.ticket.update_status', label: 'Update ticket status', risk: 'low' },
      ],
    },
  },
  {
    id: 'jira',
    name: 'Jira (Atlassian)',
    category: 'ITSM',
    description: 'Issue tracking and Jira Service Management (create/update issues, triage requests).',
    authType: 'api_key',
    tags: ['ITSM', 'GLOBAL'],
    status: 'READY',
    color: '#2684FF',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'base_url', label: 'Base URL', type: 'text', placeholder: 'https://yourdomain.atlassian.net', required: true, description: 'Atlassian cloud base URL' },
        { name: 'email', label: 'Email', type: 'text', placeholder: 'admin@company.com', required: true, description: 'Atlassian account email' },
        { name: 'api_token', label: 'API Token', type: 'password', placeholder: '••••••••', required: true, description: 'Atlassian API token' },
      ],
      testEndpoint: '/rest/api/3/myself',
      baseUrl: '',
    },
    endpoints: {
      myself: { method: 'GET', path: 'https://{base_url}/rest/api/3/myself' },
    },
    capabilities: {
      reads: ['itsm.issues'],
      writes: [
        { id: 'itsm.issue.create', label: 'Create issue', risk: 'medium' },
        { id: 'itsm.issue.update', label: 'Update issue', risk: 'low' },
      ],
    },
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'CRM',
    description: 'CRM for leads, contacts, and deals (enrichment and pipeline automation).',
    authType: 'oauth2',
    tags: ['CRM', 'GLOBAL'],
    status: 'READY',
    color: '#FF7A59',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://app.hubspot.com/oauth/authorize',
      tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
      scopes: [
        'crm.objects.contacts.read',
        'crm.objects.contacts.write',
        'crm.objects.deals.read',
        'crm.objects.deals.write',
        'crm.objects.companies.read',
        'crm.objects.companies.write',
        'tickets',
      ],
      redirectPath: `${API_CALLBACK_BASE}/hubspot`,
    },
    endpoints: {
      details: { method: 'GET', path: 'https://api.hubapi.com/account-info/v3/details' },
    },
    capabilities: {
      reads: ['sales.leads', 'sales.contacts', 'sales.deals'],
      writes: [
        { id: 'sales.lead.update', label: 'Update lead/contact', risk: 'low' },
        { id: 'sales.deal.update', label: 'Update deal stage', risk: 'low' },
      ],
    },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'PAYMENTS',
    description: 'Payments platform (transactions, refunds, and dispute workflows).',
    authType: 'api_key',
    tags: ['PAYMENTS', 'GLOBAL'],
    status: 'READY',
    color: '#635BFF',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'secret_key', label: 'Secret Key', type: 'password', placeholder: 'sk_live_...', required: true, description: 'Stripe secret key' },
      ],
      testEndpoint: 'https://api.stripe.com/v1/account',
      baseUrl: 'https://api.stripe.com',
    },
    endpoints: {
      account: { method: 'GET', path: 'https://api.stripe.com/v1/account' },
    },
    capabilities: {
      reads: ['finance.transactions', 'finance.refunds'],
      writes: [
        { id: 'finance.refund.create', label: 'Create refund', risk: 'money' },
      ],
    },
  },
  {
    id: 'cashfree',
    name: 'Cashfree',
    category: 'PAYMENTS',
    description: 'Payments platform in India (transactions and refunds).',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'PAYMENTS'],
    status: 'READY',
    color: '#0C2451',
    priority: 4,
    maturity: 'governed',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'key_id', label: 'Key ID', type: 'text', placeholder: 'rzp_live_...', required: true, description: 'Cashfree key id' },
        { name: 'key_secret', label: 'Key Secret', type: 'password', placeholder: '••••••••', required: true, description: 'Cashfree key secret' },
      ],
      testEndpoint: 'https://api.cashfree.com/v1/payments?count=1',
      baseUrl: 'https://api.cashfree.com/v1',
    },
    endpoints: {
      payments: { method: 'GET', path: 'https://api.cashfree.com/v1/payments' },
    },
    capabilities: {
      reads: ['finance.transactions', 'finance.refunds'],
      writes: [
        {
          id: 'finance.payment.list',
          label: 'List payments',
          risk: 'low',
          pack: 'finance',
          operation: 'read',
          objectType: 'payment',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Preserve payment query parameters for investigation replay'],
        },
        {
          id: 'finance.settlement.check',
          label: 'Check settlement',
          risk: 'medium',
          pack: 'finance',
          operation: 'read',
          objectType: 'settlement',
          reversible: false,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'request-result',
          constraints: ['Store settlement evidence for reconciliation workflow'],
        },
        {
          id: 'finance.refund.create',
          label: 'Create refund',
          risk: 'money',
          pack: 'finance',
          operation: 'create',
          objectType: 'refund',
          reversible: true,
          approvalDefault: true,
          trustTier: 'high-trust-operational',
          evidenceMode: 'before-after',
          constraints: ['Require amount thresholds and refund policy approval'],
        },
      ],
    },
  },
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    category: 'PRODUCTIVITY',
    description: 'Operate Gmail and Calendar directly from Zapheit, with Drive available as a secondary workspace surface.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'SSO', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#4285F4',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'openid',
        'email',
        'profile',
        'https://www.googleapis.com/auth/gmail.modify',
        'https://www.googleapis.com/auth/gmail.send',
        'https://www.googleapis.com/auth/calendar',
      ],
      redirectPath: `${API_CALLBACK_BASE}/google_workspace`,
    },
    endpoints: {
      userinfo: { method: 'GET', path: 'https://www.googleapis.com/oauth2/v3/userinfo' },
    },
    capabilities: {
      reads: ['user_profile', 'gmail.inbox.read', 'calendar.events.read'],
      writes: [
        { id: 'gmail.send_email', label: 'Send email (Gmail)', risk: 'medium', approvalDefault: true },
        { id: 'gmail.reply_email', label: 'Reply to email', risk: 'medium', approvalDefault: true },
        { id: 'gmail.forward_email', label: 'Forward email', risk: 'medium', approvalDefault: true },
        { id: 'gmail.archive_email', label: 'Archive email', risk: 'low', approvalDefault: false },
        { id: 'gmail.mark_email_read', label: 'Mark email as read', risk: 'low', approvalDefault: false },
        { id: 'gmail.mark_email_unread', label: 'Mark email as unread', risk: 'low', approvalDefault: false },
        { id: 'calendar.create_event', label: 'Create calendar event', risk: 'medium', approvalDefault: false },
        { id: 'calendar.update_event', label: 'Edit calendar event', risk: 'medium', approvalDefault: false },
        { id: 'calendar.cancel_event', label: 'Cancel calendar event', risk: 'medium', approvalDefault: true },
      ],
    },
  },
  {
    id: 'microsoft_365',
    name: 'Microsoft 365',
    category: 'PRODUCTIVITY',
    description: 'Identity + productivity telemetry across Outlook, OneDrive, Calendar, and Directory (Microsoft Graph).',
    authType: 'oauth2',
    tags: ['ENTERPRISE', 'SSO', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#D83B01',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: [
        'openid',
        'email',
        'profile',
        'offline_access',
        'User.Read',
        'Mail.ReadWrite',
        'Calendars.ReadWrite',
        'Files.ReadWrite.All',
        'Directory.Read.All',
      ],
      redirectPath: `${API_CALLBACK_BASE}/microsoft_365`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://graph.microsoft.com/v1.0/me' },
    },
    capabilities: {
      reads: ['user_profile'],
      writes: [
        { id: 'outreach.send_email', label: 'Send email (Outlook)', risk: 'medium' },
        { id: 'outreach.create_calendar_event', label: 'Create calendar invite', risk: 'medium' },
      ],
    },
  },
  {
    id: 'keka',
    name: 'Keka HR',
    category: 'HRMS',
    description: 'HRMS + payroll workflows for India. Server-to-server client credentials authentication.',
    authType: 'client_credentials',
    tags: ['INDIA PRIORITY', 'HRMS'],
    status: 'READY',
    color: '#FF6B35',
    priority: 4,
    connectionFields: [
      { name: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Enter Keka Client ID', required: true, description: 'From Keka developer settings' },
      { name: 'client_secret', label: 'Client Secret', type: 'password', placeholder: '••••••••', required: true, description: 'From Keka developer settings' },
      { name: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany', required: true, description: 'Keka subdomain (without .keka.com)' },
    ],
    endpoints: {
      token: { method: 'POST', path: 'https://{subdomain}.keka.com/oauth/token' },
      employees: { method: 'GET', path: 'https://{subdomain}.keka.com/api/v1/employees' },
    },
    capabilities: {
      reads: ['hr.employees', 'hr.attendance'],
      writes: [
        { id: 'hr.employee.update', label: 'Update employee record', risk: 'medium' },
        { id: 'hr.leave.approve', label: 'Approve leave request', risk: 'medium' },
      ],
    },
  },
  {
    id: 'cashfreex',
    name: 'CashfreeX Payroll',
    category: 'PAYROLL',
    description: 'Payroll disbursements and payout rails via CashfreeX.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'PAYROLL'],
    status: 'READY',
    color: '#0066FF',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'key_id', label: 'Key ID', type: 'text', placeholder: 'rzp_test_...', required: true, description: 'Cashfree Key ID' },
        { name: 'key_secret', label: 'Key Secret', type: 'password', placeholder: '••••••••', required: true, description: 'Cashfree Key Secret' },
        { name: 'account_id', label: 'Account ID', type: 'text', placeholder: 'acc_...', required: true, description: 'CashfreeX account identifier' },
      ],
      testEndpoint: 'https://api.cashfree.com/v1/fund_accounts',
      baseUrl: 'https://api.cashfree.com/v1',
    },
    endpoints: {
      fundAccounts: { method: 'GET', path: '/fund_accounts' },
    },
    capabilities: {
      reads: ['finance.payroll', 'finance.fund_accounts'],
      writes: [
        { id: 'finance.payout.initiate', label: 'Initiate payout', risk: 'money' },
      ],
    },
  },
  {
    id: 'deel',
    name: 'Deel',
    category: 'GLOBAL_PAYROLL',
    description: 'Global payroll + contractor operations.',
    authType: 'oauth2',
    tags: ['GLOBAL', 'PAYROLL'],
    status: 'READY',
    color: '#15357A',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://app.deel.com/oauth2/authorize',
      tokenUrl: 'https://app.deel.com/oauth2/token',
      scopes: [],
      redirectPath: `${API_CALLBACK_BASE}/deel`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://api.deel.com/rest/v2/profile' },
    },
    capabilities: {
      reads: ['hr.employees', 'hr.contracts', 'finance.payroll'],
      writes: [
        { id: 'hr.contract.create', label: 'Create contractor contract', risk: 'high' },
        { id: 'finance.payroll.approve', label: 'Approve payroll run', risk: 'money' },
      ],
    },
  },
  {
    id: 'gusto',
    name: 'Gusto',
    category: 'PAYROLL',
    description: 'US payroll + benefits operations.',
    authType: 'oauth2',
    tags: ['US PAYROLL'],
    status: 'READY',
    color: '#E87722',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://api.gusto.com/oauth/authorize',
      tokenUrl: 'https://api.gusto.com/oauth/token',
      scopes: ['public', 'webhook_subscriptions:read', 'webhook_subscriptions:write'],
      redirectPath: `${API_CALLBACK_BASE}/gusto`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://api.gusto.com/v1/me' },
    },
    capabilities: {
      reads: ['hr.employees', 'finance.payroll'],
      writes: [
        { id: 'finance.payroll.run', label: 'Run payroll', risk: 'money' },
      ],
    },
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'COMMUNICATION',
    description: 'Slack workspace connection for channel access and message sending.',
    authType: 'oauth2',
    tags: ['COMMUNICATION', 'GLOBAL'],
    status: 'READY',
    color: '#4A154B',
    priority: 4,
    maturity: 'governed',
    trustTier: 'controlled-write',
    oauthConfig: {
      authorizationUrl: 'https://slack.com/oauth/v2/authorize',
      tokenUrl: 'https://slack.com/api/oauth.v2.access',
      scopes: [
        'channels:read',
        'channels:history',
        'groups:read',
        'groups:history',
        'chat:write',
        'users:read',
        'users:read.email',
      ],
      redirectPath: `${API_CALLBACK_BASE}/slack`,
    },
    endpoints: {
      authTest: { method: 'POST', path: 'https://slack.com/api/auth.test' },
    },
    capabilities: {
      reads: ['comms.channels', 'comms.users'],
      writes: [
        {
          id: 'comms.channel.history',
          label: 'Read channel history',
          risk: 'low',
          pack: 'it',
          operation: 'read',
          objectType: 'message',
          reversible: false,
          approvalDefault: false,
          trustTier: 'observe-only',
          evidenceMode: 'request-result',
          constraints: ['Respect workspace channel access boundaries'],
        },
        {
          id: 'comms.message.send',
          label: 'Send Slack message',
          risk: 'medium',
          pack: 'it',
          operation: 'create',
          objectType: 'message',
          reversible: true,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'before-after',
          constraints: ['Record destination channel and reviewer rationale for outbound comms'],
        },
        {
          id: 'comms.channel.create',
          label: 'Create Slack channel',
          risk: 'low',
          pack: 'it',
          operation: 'create',
          objectType: 'channel',
          reversible: true,
          approvalDefault: false,
          trustTier: 'controlled-write',
          evidenceMode: 'request-result',
          constraints: ['Limit new channels to approved naming patterns where policy requires'],
        },
      ],
    },
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'COLLABORATION',
    description: 'Collaboration rail via Microsoft Graph.',
    authType: 'oauth2',
    tags: ['ENTERPRISE', 'COLLABORATION'],
    status: 'READY',
    color: '#6264A7',
    priority: 4,
    oauthConfig: {
      // Teams permissions are work/school-account-only — must use 'organizations'
      // endpoint, not 'common' (which includes personal accounts that don't have Teams).
      authorizationUrl: 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token',
      scopes: ['openid', 'offline_access', 'User.Read', 'Channel.ReadBasic.All', 'ChannelMessage.Send', 'Team.ReadBasic.All'],
      redirectPath: `${API_CALLBACK_BASE}/teams`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://graph.microsoft.com/v1.0/me' },
    },
    capabilities: {
      reads: ['comms.channels', 'comms.users'],
      writes: [
        { id: 'comms.message.send', label: 'Send Teams channel message', risk: 'medium' },
      ],
    },
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business (Cloud API)',
    category: 'COMMUNICATION',
    description: 'WhatsApp messaging via Meta Cloud API for alerts, workflows, and conversations.',
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'MESSAGING'],
    status: 'READY',
    color: '#25D366',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'access_token', label: 'Access Token', type: 'password', placeholder: 'Meta access token', required: true, description: 'From Meta Business dashboard' },
        { name: 'phone_number_id', label: 'Phone Number ID', type: 'text', placeholder: '1234567890', required: true, description: 'Phone Number ID from WhatsApp Business' },
        { name: 'waba_id', label: 'WABA ID', type: 'text', placeholder: '0987654321', required: true, description: 'WhatsApp Business Account ID' },
      ],
      testEndpoint: 'https://graph.facebook.com/v21.0',
      baseUrl: 'https://graph.facebook.com/v21.0',
    },
    endpoints: {
      phone: { method: 'GET', path: '/{phone_number_id}' },
      messages: { method: 'POST', path: '/{phone_number_id}/messages' },
      templates: { method: 'GET', path: '/{waba_id}/message_templates' },
    },
    capabilities: {
      reads: ['comms.whatsapp.contacts', 'comms.whatsapp.templates'],
      writes: [
        { id: 'comms.whatsapp.send', label: 'Send WhatsApp message', risk: 'medium' },
        { id: 'comms.whatsapp.template', label: 'Send template message', risk: 'medium' },
      ],
    },
  },
  {
    id: 'okta',
    name: 'Okta / Auth0',
    category: 'IAM',
    description: 'Identity governance and directory sync via Okta or Auth0.',
    authType: 'oauth2',
    tags: ['IDENTITY', 'ENTERPRISE'],
    status: 'COMING_SOON',
    color: '#007DC1',
    priority: 4,
    connectionFields: [
      { name: 'domain', label: 'Auth0 / Okta Domain', type: 'text', placeholder: 'your-tenant.us.auth0.com', required: true, description: 'Your Auth0 or Okta domain (no https://)' },
    ],
    oauthConfig: {
      authorizationUrl: 'https://{domain}/authorize',
      tokenUrl: 'https://{domain}/oauth/token',
      scopes: ['openid', 'profile', 'email'],
      redirectPath: `${API_CALLBACK_BASE}/okta`,
    },
    endpoints: {
      userinfo: { method: 'GET', path: 'https://{domain}/userinfo' },
    },
    capabilities: {
      reads: ['identity.users', 'identity.groups'],
      writes: [
        { id: 'identity.user.provision', label: 'Provision user account', risk: 'high' },
        { id: 'identity.user.deactivate', label: 'Deactivate user', risk: 'high' },
        { id: 'identity.group.assign', label: 'Assign user to group', risk: 'medium' },
      ],
    },
  },
  {
    id: 'onelogin',
    name: 'OneLogin',
    category: 'IAM',
    description: 'Identity governance and user lifecycle operations through OneLogin.',
    authType: 'api_key',
    tags: ['IDENTITY', 'ENTERPRISE'],
    status: 'COMING_SOON',
    color: '#5A4BFF',
    priority: 4,
    maturity: 'action-ready',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'domain', label: 'OneLogin Domain', type: 'text', placeholder: 'example.onelogin.com', required: true, description: 'Your OneLogin domain (no https://)' },
        { name: 'client_id', label: 'Client ID', type: 'text', placeholder: 'Enter OneLogin client ID', required: true, description: 'API credential client ID' },
        { name: 'client_secret', label: 'Client Secret', type: 'password', placeholder: 'Enter OneLogin client secret', required: true, description: 'API credential client secret' },
      ],
      testEndpoint: 'https://<domain>/api/1/users',
      baseUrl: 'https://<domain>',
    },
    endpoints: {
      token: { method: 'POST', path: 'https://{domain}/auth/oauth2/v2/token' },
      users: { method: 'GET', path: 'https://{domain}/api/1/users' },
      roles: { method: 'GET', path: 'https://{domain}/api/2/roles' },
    },
    capabilities: {
      reads: ['identity.users', 'identity.roles'],
      writes: [
        { id: 'identity.user.provision', label: 'Provision OneLogin user', risk: 'high' },
        { id: 'identity.user.deactivate', label: 'Deactivate OneLogin user', risk: 'high' },
        { id: 'identity.group.assign', label: 'Assign OneLogin role', risk: 'medium' },
      ],
    },
  },
  {
    id: 'kandji',
    name: 'Kandji',
    category: 'ITSM',
    description: 'Apple device management, endpoint posture, and blueprint-driven policy operations.',
    authType: 'api_key',
    tags: ['IT', 'SECURITY', 'ENDPOINT'],
    status: 'COMING_SOON',
    color: '#111827',
    priority: 4,
    maturity: 'action-ready',
    trustTier: 'high-trust-operational',
    apiKeyConfig: {
      requiredFields: [
        { name: 'base_url', label: 'Tenant API URL', type: 'text', placeholder: 'https://tenant.api.kandji.io', required: true, description: 'Tenant-specific Kandji API URL' },
        { name: 'api_key', label: 'API Token', type: 'password', placeholder: 'Enter Kandji API token', required: true, description: 'Tenant-level bearer token from Kandji' },
      ],
      testEndpoint: '{base_url}/devices',
      baseUrl: 'https://<tenant-api-url>',
    },
    endpoints: {
      devices: { method: 'GET', path: '{base_url}/devices' },
      blueprints: { method: 'GET', path: '{base_url}/blueprints' },
    },
    capabilities: {
      reads: ['it.devices', 'it.blueprints', 'it.posture'],
      writes: [
        { id: 'it.device.lock', label: 'Lock managed device', risk: 'high' },
        { id: 'it.device.erase', label: 'Erase managed device', risk: 'high' },
        { id: 'it.blueprint.assign', label: 'Assign device blueprint', risk: 'medium' },
      ],
    },
  },
  {
    id: 'flock',
    name: 'Flock',
    category: 'COMMUNICATION',
    description: 'Indian team messaging platform (Slack alternative).',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'COMMUNICATION'],
    status: 'COMING_SOON',
    color: '#0BA8E0',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://dev.flock.com/oauth/authorize',
      tokenUrl: 'https://dev.flock.com/oauth/token',
      scopes: ['chat:read', 'chat:write', 'users:read'],
      redirectPath: `${API_CALLBACK_BASE}/flock`,
    },
    endpoints: {
      users: { method: 'GET', path: 'https://api.flock.com/v1/users.list' },
    },
    capabilities: {
      reads: [],
      writes: [
        { id: 'comms.message.send', label: 'Send Flock message', risk: 'medium' },
      ],
    },
  },
  {
    id: 'epfo',
    name: 'EPFO',
    category: 'COMPLIANCE',
    description: "Employees' Provident Fund Organization. PF compliance telemetry and filing posture.",
    authType: 'api_key',
    tags: ['INDIA PRIORITY', 'GOVERNMENT', 'COMPLIANCE'],
    status: 'COMING_SOON',
    color: '#1D4ED8',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'establishment_id', label: 'Establishment ID', type: 'text', placeholder: 'Enter EPF Establishment ID', required: true, description: 'EPFO establishment id' },
        { name: 'api_key', label: 'API Key', type: 'password', placeholder: 'Enter API Key', required: true, description: 'EPFO API key' },
        { name: 'dsc', label: 'DSC (Digital Signature Certificate)', type: 'password', placeholder: 'Digital Signature', required: true, description: 'Digital signature certificate material' },
      ],
      testEndpoint: 'https://api.epfindia.gov.in/v1/establishment',
      baseUrl: 'https://api.epfindia.gov.in/v1',
    },
    endpoints: {
      establishment: { method: 'GET', path: '/establishment' },
    },
    capabilities: {
      reads: ['compliance.pf_status'],
      writes: [
        { id: 'compliance.pf.file', label: 'File PF return', risk: 'high' },
      ],
    },
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'CRM',
    description: 'Enterprise CRM for leads, contacts, opportunities, and pipeline automation.',
    authType: 'oauth2',
    tags: ['CRM', 'GLOBAL', 'ENTERPRISE'],
    status: 'READY',
    color: '#00A1E0',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://login.salesforce.com/services/oauth2/authorize',
      tokenUrl: 'https://login.salesforce.com/services/oauth2/token',
      scopes: ['api', 'refresh_token', 'offline_access'],
      redirectPath: `${API_CALLBACK_BASE}/salesforce`,
    },
    endpoints: {
      userinfo: { method: 'GET', path: 'https://login.salesforce.com/services/oauth2/userinfo' },
      leads: { method: 'GET', path: '/services/data/v59.0/sobjects/Lead' },
      contacts: { method: 'GET', path: '/services/data/v59.0/sobjects/Contact' },
      opportunities: { method: 'GET', path: '/services/data/v59.0/sobjects/Opportunity' },
    },
    capabilities: {
      reads: ['sales.leads', 'sales.contacts', 'sales.opportunities'],
      writes: [
        { id: 'sales.lead.create', label: 'Create lead', risk: 'medium' },
        { id: 'sales.lead.update', label: 'Update lead / contact', risk: 'low' },
        { id: 'sales.opportunity.update', label: 'Update opportunity stage', risk: 'low' },
      ],
    },
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'SUPPORT',
    description: 'Customer messaging and support platform for live chat, tickets, and product tours.',
    authType: 'oauth2',
    tags: ['SUPPORT', 'GLOBAL'],
    status: 'READY',
    color: '#1F8DED',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://app.intercom.com/oauth',
      tokenUrl: 'https://api.intercom.io/auth/eagle/token',
      scopes: ['conversations_read', 'conversations_write', 'contacts_read', 'contacts_write'],
      redirectPath: `${API_CALLBACK_BASE}/intercom`,
    },
    endpoints: {
      me: { method: 'GET', path: 'https://api.intercom.io/me' },
      conversations: { method: 'GET', path: 'https://api.intercom.io/conversations' },
      contacts: { method: 'GET', path: 'https://api.intercom.io/contacts' },
    },
    capabilities: {
      reads: ['support.tickets', 'support.contacts'],
      writes: [
        { id: 'support.ticket.reply', label: 'Reply to conversation', risk: 'medium' },
        { id: 'support.ticket.update_status', label: 'Close / snooze conversation', risk: 'low' },
      ],
    },
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'FINANCE',
    description: 'Accounting platform for invoices, expenses, payroll reporting, and financial analytics.',
    authType: 'oauth2',
    tags: ['FINANCE', 'ACCOUNTING', 'GLOBAL'],
    status: 'COMING_SOON',
    color: '#2CA01C',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://appcenter.intuit.com/connect/oauth2',
      tokenUrl: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',
      scopes: ['com.intuit.quickbooks.accounting'],
      redirectPath: `${API_CALLBACK_BASE}/quickbooks`,
    },
    endpoints: {
      companyInfo: { method: 'GET', path: '/v3/company/{realmId}/companyinfo/{realmId}' },
      invoices: { method: 'GET', path: '/v3/company/{realmId}/query?query=select * from Invoice' },
      expenses: { method: 'GET', path: '/v3/company/{realmId}/query?query=select * from Purchase' },
    },
    capabilities: {
      reads: ['finance.invoices', 'finance.expenses', 'finance.transactions'],
      writes: [
        { id: 'finance.invoice.create', label: 'Create invoice', risk: 'money' },
        { id: 'finance.expense.create', label: 'Log expense', risk: 'medium' },
      ],
    },
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    category: 'ITSM',
    description: 'Enterprise IT service management for incidents, change requests, and asset tracking.',
    authType: 'api_key',
    tags: ['ITSM', 'ENTERPRISE', 'GLOBAL'],
    status: 'READY',
    color: '#81B5A1',
    priority: 4,
    apiKeyConfig: {
      requiredFields: [
        { name: 'instance', label: 'Instance Name', type: 'text', placeholder: 'yourcompany', required: true, description: 'ServiceNow instance name (yourcompany.service-now.com)' },
        { name: 'username', label: 'Username', type: 'text', placeholder: 'admin', required: true, description: 'ServiceNow username' },
        { name: 'password', label: 'Password', type: 'password', placeholder: '••••••••', required: true, description: 'ServiceNow password or API token' },
      ],
      testEndpoint: '/api/now/table/sys_user?sysparm_limit=1',
      baseUrl: 'https://{instance}.service-now.com',
    },
    endpoints: {
      incidents: { method: 'GET', path: '/api/now/table/incident' },
      createIncident: { method: 'POST', path: '/api/now/table/incident' },
      changeRequests: { method: 'GET', path: '/api/now/table/change_request' },
    },
    capabilities: {
      reads: ['itsm.incidents', 'itsm.changes', 'itsm.assets'],
      writes: [
        { id: 'itsm.incident.create', label: 'Create incident', risk: 'medium' },
        { id: 'itsm.incident.update', label: 'Update incident status', risk: 'low' },
        { id: 'itsm.change.create', label: 'Create change request', risk: 'high' },
      ],
    },
  },
];

export const PHASE5_INTEGRATIONS: IntegrationSpec[] = [
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'COMMUNICATION',
    description: 'Schedule and manage meetings, pull recordings, and automate follow-ups.',
    authType: 'oauth2',
    tags: ['COMMUNICATION', 'GLOBAL'],
    status: 'READY',
    color: '#2D8CFF',
    priority: 2,
    oauthConfig: {
      authorizationUrl: 'https://zoom.us/oauth/authorize',
      tokenUrl: 'https://zoom.us/oauth/token',
      scopes: ['meeting:read:admin', 'recording:read:admin', 'user:read:admin'],
      redirectPath: `${API_CALLBACK_BASE}/zoom`,
    },
    endpoints: {
      meetings: { method: 'GET', path: '/v2/users/me/meetings' },
      recordings: { method: 'GET', path: '/v2/users/me/recordings' },
    },
    capabilities: {
      reads: ['comms.meetings', 'comms.recordings'],
      writes: [
        { id: 'comms.meeting.create', label: 'Schedule meeting', risk: 'low' },
        { id: 'comms.meeting.delete', label: 'Cancel meeting', risk: 'medium' },
      ],
    },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'DEVOPS',
    description: 'DevOps platform — source code management, CI/CD pipelines, and security scanning.',
    authType: 'oauth2',
    tags: ['DEVOPS', 'GLOBAL'],
    status: 'READY',
    color: '#FC6D26',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://gitlab.com/oauth/authorize',
      tokenUrl: 'https://gitlab.com/oauth/token',
      scopes: ['api', 'read_user', 'read_repository'],
      redirectPath: `${API_CALLBACK_BASE}/gitlab`,
    },
    endpoints: {
      projects: { method: 'GET', path: '/api/v4/projects' },
      issues: { method: 'GET', path: '/api/v4/projects/{id}/issues' },
      mergeRequests: { method: 'GET', path: '/api/v4/projects/{id}/merge_requests' },
    },
    capabilities: {
      reads: ['devops.repos', 'devops.issues', 'devops.pipelines'],
      writes: [
        { id: 'devops.issue.create', label: 'Create issue', risk: 'medium' },
        { id: 'devops.mr.merge', label: 'Merge merge request', risk: 'high' },
      ],
    },
  },
  {
    id: 'xero',
    name: 'Xero',
    category: 'FINANCE',
    description: 'Cloud accounting — invoices, bank reconciliation, and financial reporting.',
    authType: 'oauth2',
    tags: ['FINANCE', 'GLOBAL'],
    status: 'READY',
    color: '#13B5EA',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://login.xero.com/identity/connect/authorize',
      tokenUrl: 'https://identity.xero.com/connect/token',
      scopes: ['openid', 'profile', 'email', 'accounting.transactions', 'accounting.contacts', 'offline_access'],
      redirectPath: `${API_CALLBACK_BASE}/xero`,
    },
    endpoints: {
      invoices: { method: 'GET', path: '/api.xro/2.0/Invoices' },
      contacts: { method: 'GET', path: '/api.xro/2.0/Contacts' },
      accounts: { method: 'GET', path: '/api.xro/2.0/Accounts' },
    },
    capabilities: {
      reads: ['finance.invoices', 'finance.contacts', 'finance.accounts'],
      writes: [
        { id: 'finance.invoice.create', label: 'Create invoice', risk: 'money' },
        { id: 'finance.payment.record', label: 'Record payment', risk: 'money' },
      ],
    },
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'PRODUCTIVITY',
    description: 'Collaborative design platform — read files, comments, and component libraries.',
    authType: 'oauth2',
    tags: ['DESIGN', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#F24E1E',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://www.figma.com/oauth',
      tokenUrl: 'https://www.figma.com/api/oauth/token',
      scopes: ['files:read', 'file_comments:write'],
      redirectPath: `${API_CALLBACK_BASE}/figma`,
    },
    endpoints: {
      files: { method: 'GET', path: '/v1/files/{file_key}' },
      projects: { method: 'GET', path: '/v1/teams/{team_id}/projects' },
    },
    capabilities: {
      reads: ['productivity.design_files', 'productivity.comments'],
      writes: [
        { id: 'productivity.comment.post', label: 'Post design comment', risk: 'low' },
      ],
    },
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'PRODUCTIVITY',
    description: 'Project management and task tracking — create tasks, update projects, and automate workflows.',
    authType: 'oauth2',
    tags: ['PRODUCTIVITY', 'PROJECT_MANAGEMENT'],
    status: 'READY',
    color: '#F06A6A',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://app.asana.com/-/oauth_authorize',
      tokenUrl: 'https://app.asana.com/-/oauth_token',
      scopes: ['default'],
      redirectPath: `${API_CALLBACK_BASE}/asana`,
    },
    endpoints: {
      tasks: { method: 'GET', path: '/api/1.0/tasks' },
      projects: { method: 'GET', path: '/api/1.0/projects' },
      user: { method: 'GET', path: '/api/1.0/users/me' },
    },
    capabilities: {
      reads: ['productivity.tasks', 'productivity.projects'],
      writes: [
        { id: 'productivity.task.create', label: 'Create task', risk: 'low' },
        { id: 'productivity.task.update', label: 'Update task', risk: 'low' },
      ],
    },
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'PRODUCTIVITY',
    description: 'Work OS — manage projects, teams, and workflows in one visual platform.',
    authType: 'oauth2',
    tags: ['PRODUCTIVITY', 'PROJECT_MANAGEMENT'],
    status: 'READY',
    color: '#FF3D57',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://auth.monday.com/oauth2/authorize',
      tokenUrl: 'https://auth.monday.com/oauth2/token',
      scopes: ['boards:read', 'boards:write', 'users:read', 'teams:read'],
      redirectPath: `${API_CALLBACK_BASE}/monday`,
    },
    endpoints: {
      boards: { method: 'POST', path: '/v2' },
    },
    capabilities: {
      reads: ['productivity.boards', 'productivity.items'],
      writes: [
        { id: 'productivity.item.create', label: 'Create board item', risk: 'low' },
        { id: 'productivity.item.update', label: 'Update board item', risk: 'low' },
      ],
    },
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: 'OTHER',
    description: 'Email marketing — manage campaigns, audiences, and automations.',
    authType: 'oauth2',
    tags: ['MARKETING', 'EMAIL'],
    status: 'READY',
    color: '#FFE01B',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://login.mailchimp.com/oauth2/authorize',
      tokenUrl: 'https://login.mailchimp.com/oauth2/token',
      scopes: [],
      redirectPath: `${API_CALLBACK_BASE}/mailchimp`,
    },
    endpoints: {
      lists: { method: 'GET', path: '/3.0/lists' },
      campaigns: { method: 'GET', path: '/3.0/campaigns' },
    },
    capabilities: {
      reads: ['marketing.audiences', 'marketing.campaigns'],
      writes: [
        { id: 'marketing.campaign.create', label: 'Create campaign', risk: 'medium' },
        { id: 'marketing.subscriber.add', label: 'Add subscriber', risk: 'low' },
      ],
    },
  },
  {
    id: 'box',
    name: 'Box',
    category: 'PRODUCTIVITY',
    description: 'Cloud content management — secure file storage, sharing, and collaboration.',
    authType: 'oauth2',
    tags: ['STORAGE', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#0061D5',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://account.box.com/api/oauth2/authorize',
      tokenUrl: 'https://api.box.com/oauth2/token',
      scopes: [],
      redirectPath: `${API_CALLBACK_BASE}/box`,
    },
    endpoints: {
      files: { method: 'GET', path: '/2.0/files/{id}' },
      folders: { method: 'GET', path: '/2.0/folders/{id}/items' },
    },
    capabilities: {
      reads: ['productivity.files', 'productivity.folders'],
      writes: [
        { id: 'productivity.file.upload', label: 'Upload file', risk: 'low' },
        { id: 'productivity.folder.create', label: 'Create folder', risk: 'low' },
      ],
    },
  },
  {
    id: 'dropbox_business',
    name: 'Dropbox Business',
    category: 'PRODUCTIVITY',
    description: 'Cloud storage and team collaboration — sync files and manage shared folders.',
    authType: 'oauth2',
    tags: ['STORAGE', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#0061FF',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://www.dropbox.com/oauth2/authorize',
      tokenUrl: 'https://api.dropboxapi.com/oauth2/token',
      scopes: ['account_info.read', 'files.metadata.read', 'sharing.read'],
      redirectPath: `${API_CALLBACK_BASE}/dropbox_business`,
    },
    endpoints: {
      account: { method: 'POST', path: '/2/users/get_current_account' },
      files: { method: 'POST', path: '/2/files/list_folder' },
    },
    capabilities: {
      reads: ['productivity.files', 'productivity.folders'],
      writes: [
        { id: 'productivity.file.upload', label: 'Upload file', risk: 'low' },
        { id: 'productivity.folder.share', label: 'Share folder', risk: 'medium' },
      ],
    },
  },
  {
    id: 'google_chat',
    name: 'Google Chat',
    category: 'COMMUNICATION',
    description: 'Send messages and notifications to Google Chat spaces and DMs.',
    authType: 'oauth2',
    tags: ['COMMUNICATION', 'GOOGLE'],
    status: 'READY',
    color: '#00897B',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scopes: [
        'https://www.googleapis.com/auth/chat.spaces.readonly',
        'https://www.googleapis.com/auth/chat.messages',
      ],
      redirectPath: `${API_CALLBACK_BASE}/google_chat`,
    },
    endpoints: {
      spaces: { method: 'GET', path: '/v1/spaces' },
      messages: { method: 'POST', path: '/v1/spaces/{name}/messages' },
    },
    capabilities: {
      reads: ['comms.spaces'],
      writes: [
        { id: 'comms.message.send', label: 'Send Chat message', risk: 'low' },
      ],
    },
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'PRODUCTIVITY',
    description: 'Automated scheduling — book meetings and manage availability.',
    authType: 'oauth2',
    tags: ['PRODUCTIVITY', 'SCHEDULING'],
    status: 'READY',
    color: '#006BFF',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://auth.calendly.com/oauth/authorize',
      tokenUrl: 'https://auth.calendly.com/oauth/token',
      scopes: ['default'],
      redirectPath: `${API_CALLBACK_BASE}/calendly`,
    },
    endpoints: {
      user: { method: 'GET', path: '/v2/users/me' },
      eventTypes: { method: 'GET', path: '/v2/event_types' },
      events: { method: 'GET', path: '/v2/scheduled_events' },
    },
    capabilities: {
      reads: ['productivity.schedules', 'productivity.events'],
      writes: [
        { id: 'productivity.event.cancel', label: 'Cancel event', risk: 'medium' },
      ],
    },
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'PRODUCTIVITY',
    description: 'Online collaborative whiteboard — create boards, add items, and export content.',
    authType: 'oauth2',
    tags: ['PRODUCTIVITY', 'DESIGN'],
    status: 'READY',
    color: '#FFD02F',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://miro.com/oauth/authorize',
      tokenUrl: 'https://api.miro.com/v1/oauth/token',
      scopes: ['boards:read', 'boards:write'],
      redirectPath: `${API_CALLBACK_BASE}/miro`,
    },
    endpoints: {
      boards: { method: 'GET', path: '/v2/boards' },
      items: { method: 'GET', path: '/v2/boards/{board_id}/items' },
    },
    capabilities: {
      reads: ['productivity.boards'],
      writes: [
        { id: 'productivity.board.create', label: 'Create board', risk: 'low' },
        { id: 'productivity.item.add', label: 'Add board item', risk: 'low' },
      ],
    },
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'PRODUCTIVITY',
    description: 'Design and visual content creation — generate branded assets and templates.',
    authType: 'oauth2',
    tags: ['DESIGN', 'PRODUCTIVITY'],
    status: 'READY',
    color: '#00C4CC',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://www.canva.com/api/oauth/authorize',
      tokenUrl: 'https://api.canva.com/rest/v1/oauth/token',
      scopes: ['asset:read', 'design:content:read', 'profile:read'],
      redirectPath: `${API_CALLBACK_BASE}/canva`,
    },
    endpoints: {
      designs: { method: 'GET', path: '/rest/v1/designs' },
      user: { method: 'GET', path: '/rest/v1/users/me' },
    },
    capabilities: {
      reads: ['productivity.designs'],
      writes: [
        { id: 'productivity.design.create', label: 'Create design', risk: 'low' },
      ],
    },
  },
  {
    id: 'zoho_crm',
    name: 'Zoho CRM',
    category: 'CRM',
    description: 'Complete CRM for Indian businesses — leads, deals, and customer lifecycle management.',
    authType: 'oauth2',
    tags: ['INDIA PRIORITY', 'CRM', 'SALES'],
    status: 'READY',
    color: '#E42527',
    priority: 2,
    oauthConfig: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      scopes: ['ZohoCRM.modules.ALL', 'ZohoCRM.settings.ALL'],
      redirectPath: `${API_CALLBACK_BASE}/zoho_crm`,
    },
    endpoints: {
      leads: { method: 'GET', path: '/crm/v5/Leads' },
      contacts: { method: 'GET', path: '/crm/v5/Contacts' },
      deals: { method: 'GET', path: '/crm/v5/Deals' },
    },
    capabilities: {
      reads: ['sales.leads', 'sales.contacts', 'sales.deals'],
      writes: [
        { id: 'sales.lead.create', label: 'Create lead', risk: 'low' },
        { id: 'sales.deal.update', label: 'Update deal', risk: 'low' },
      ],
    },
  },
  {
    id: 'aircall',
    name: 'Aircall',
    category: 'SUPPORT',
    description: 'Cloud phone system for support and sales — call routing, IVR, and analytics.',
    authType: 'oauth2',
    tags: ['SUPPORT', 'TELEPHONY'],
    status: 'READY',
    color: '#00D55B',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://dashboard.aircall.io/oauth/authorize',
      tokenUrl: 'https://api.aircall.io/v1/oauth/token',
      scopes: ['public_api:read'],
      redirectPath: `${API_CALLBACK_BASE}/aircall`,
    },
    endpoints: {
      calls: { method: 'GET', path: '/v1/calls' },
      users: { method: 'GET', path: '/v1/users' },
      numbers: { method: 'GET', path: '/v1/numbers' },
    },
    capabilities: {
      reads: ['support.calls', 'support.users'],
      writes: [
        { id: 'support.call.tag', label: 'Tag call', risk: 'low' },
      ],
    },
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'COMMUNICATION',
    description: 'Record and share screen videos — automate onboarding videos and tutorials.',
    authType: 'oauth2',
    tags: ['COMMUNICATION', 'VIDEO'],
    status: 'READY',
    color: '#625DF5',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://www.loom.com/oauth2/authorize',
      tokenUrl: 'https://www.loom.com/oauth2/token',
      scopes: ['clips:read', 'spaces:read'],
      redirectPath: `${API_CALLBACK_BASE}/loom`,
    },
    endpoints: {
      videos: { method: 'GET', path: '/v1/videos' },
      spaces: { method: 'GET', path: '/v1/spaces' },
    },
    capabilities: {
      reads: ['comms.videos', 'comms.spaces'],
      writes: [
        { id: 'comms.video.share', label: 'Share video', risk: 'low' },
      ],
    },
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    category: 'SUPPORT',
    description: 'Customer support helpdesk built for e-commerce — Shopify, WooCommerce, and more.',
    authType: 'oauth2',
    tags: ['SUPPORT', 'E_COMMERCE'],
    status: 'READY',
    color: '#1B4DFF',
    priority: 4,
    oauthConfig: {
      authorizationUrl: 'https://accounts.gorgias.com/oauth/authorize',
      tokenUrl: 'https://accounts.gorgias.com/oauth/token',
      scopes: ['openid', 'email', 'profile', 'tickets:read', 'tickets:write'],
      redirectPath: `${API_CALLBACK_BASE}/gorgias`,
    },
    endpoints: {
      tickets: { method: 'GET', path: '/api/tickets' },
      customers: { method: 'GET', path: '/api/customers' },
    },
    capabilities: {
      reads: ['support.tickets', 'support.customers'],
      writes: [
        { id: 'support.ticket.reply', label: 'Reply to ticket', risk: 'medium' },
        { id: 'support.ticket.close', label: 'Close ticket', risk: 'low' },
      ],
    },
  },
  {
    id: 'azure',
    name: 'Azure',
    category: 'DEVOPS',
    description: 'Microsoft Azure cloud services — manage resources, VMs, and DevOps pipelines.',
    authType: 'oauth2',
    tags: ['CLOUD', 'IT', 'ENTERPRISE'],
    status: 'READY',
    color: '#0089D6',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: ['https://management.azure.com/user_impersonation', 'offline_access', 'openid', 'profile'],
      redirectPath: `${API_CALLBACK_BASE}/azure`,
    },
    endpoints: {
      subscriptions: { method: 'GET', path: '/subscriptions?api-version=2022-12-01' },
      resourceGroups: { method: 'GET', path: '/subscriptions/{id}/resourcegroups?api-version=2021-04-01' },
    },
    capabilities: {
      reads: ['it.resources', 'it.subscriptions'],
      writes: [
        { id: 'it.resource.create', label: 'Create Azure resource', risk: 'high' },
      ],
    },
  },
  {
    id: 'microsoft_entra',
    name: 'Microsoft Entra ID',
    category: 'IAM',
    description: 'Identity and access management — users, groups, and conditional access policies.',
    authType: 'oauth2',
    tags: ['IDENTITY', 'IT', 'ENTERPRISE'],
    status: 'READY',
    color: '#0078D4',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: [
        'https://graph.microsoft.com/User.Read',
        'https://graph.microsoft.com/Directory.Read.All',
        'offline_access',
      ],
      redirectPath: `${API_CALLBACK_BASE}/microsoft_entra`,
    },
    endpoints: {
      users: { method: 'GET', path: '/v1.0/users' },
      groups: { method: 'GET', path: '/v1.0/groups' },
    },
    capabilities: {
      reads: ['it.users', 'it.groups'],
      writes: [
        { id: 'it.user.provision', label: 'Provision user', risk: 'high' },
        { id: 'it.user.disable', label: 'Disable user account', risk: 'high' },
      ],
    },
  },
  {
    id: 'power_bi',
    name: 'Power BI',
    category: 'OTHER',
    description: "Microsoft's BI tool — connect to datasets, trigger refreshes, and embed reports.",
    authType: 'oauth2',
    tags: ['ANALYTICS', 'MICROSOFT'],
    status: 'READY',
    color: '#F2C811',
    priority: 3,
    oauthConfig: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      scopes: [
        'https://analysis.windows.net/powerbi/api/Dataset.Read.All',
        'https://analysis.windows.net/powerbi/api/Report.Read.All',
        'offline_access',
      ],
      redirectPath: `${API_CALLBACK_BASE}/power_bi`,
    },
    endpoints: {
      datasets: { method: 'GET', path: '/v1.0/myorg/datasets' },
      reports: { method: 'GET', path: '/v1.0/myorg/reports' },
    },
    capabilities: {
      reads: ['analytics.datasets', 'analytics.reports'],
      writes: [
        { id: 'analytics.dataset.refresh', label: 'Trigger dataset refresh', risk: 'low' },
      ],
    },
  },
];

export const IMPLEMENTED_INTEGRATIONS: IntegrationSpec[] = [
  INTERNAL_INTEGRATION,
  ...PHASE1_INTEGRATIONS,
  ...PHASE2_INTEGRATIONS,
  ...PHASE3_INTEGRATIONS,
  ...PHASE4_INTEGRATIONS,
  ...PHASE5_INTEGRATIONS,
];

export function getIntegrationSpec(id: string) {
  return IMPLEMENTED_INTEGRATIONS.find((spec) => spec.id === id) || null;
}
