// ---------------------------------------------------------------------------
// Synthesized Rules API
// Exposes proposed action policies generated by the Seniority Engine's
// rule-synthesis process (3+ repeated human denials of the same action).
// ---------------------------------------------------------------------------

import { Router, type Request, type Response } from 'express';
import { requirePermission } from '../middleware/rbac';
import { supabaseRestAsUser, eq } from '../lib/supabase-rest';
import { getOrgId, getUserJwt, errorResponse } from '../lib/route-helpers';
import { applySynthesizedRuleDecision } from '../lib/synthesized-rules';

const router = Router();

// GET /api/rules/synthesized — list proposed synthesized rules for the org
router.get('/synthesized', requirePermission('policies.manage'), async (req: Request, res: Response) => {
  try {
    const orgId = getOrgId(req);
    if (!orgId) return res.status(400).json({ success: false, error: 'Organization not found' });

    const status = typeof req.query.status === 'string' ? req.query.status : 'proposed';
    const requestedLimit = Number(req.query.limit);
    const limit = Number.isFinite(requestedLimit)
      ? Math.min(Math.max(Math.trunc(requestedLimit), 1), 200)
      : 50;
    const q = new URLSearchParams();
    q.set('organization_id', eq(orgId));
    q.set('status', eq(status));
    q.set('order', 'created_at.desc');
    q.set('limit', String(limit));

    const rows = (await supabaseRestAsUser(getUserJwt(req), 'synthesized_rules', q)) as any[];
    return res.json({ success: true, data: rows || [] });
  } catch (err: any) {
    return errorResponse(res, err);
  }
});

// PATCH /api/rules/synthesized/:id — accept or dismiss a proposed rule
router.patch('/synthesized/:id', requirePermission('policies.manage'), async (req: Request, res: Response) => {
  try {
    const orgId = getOrgId(req);
    if (!orgId) return res.status(400).json({ success: false, error: 'Organization not found' });

    const { id } = req.params;
    const { status } = req.body as { status: string };

    if (status !== 'accepted' && status !== 'dismissed') {
      return res.status(400).json({ success: false, error: 'status must be "accepted" or "dismissed"' });
    }

    // Fetch the rule to get proposed_policy
    const q = new URLSearchParams();
    q.set('id', eq(id));
    q.set('organization_id', eq(orgId));
    q.set('limit', '1');
    const rows = (await supabaseRestAsUser(getUserJwt(req), 'synthesized_rules', q)) as any[];
    const rule = rows?.[0];
    if (!rule) return res.status(404).json({ success: false, error: 'Synthesized rule not found' });

    await applySynthesizedRuleDecision(orgId, rule, status);

    return res.json({ success: true, data: { id, status } });
  } catch (err: any) {
    return errorResponse(res, err);
  }
});

export default router;
