import type React from 'react';
import {
  Code,
  Database,
  FlaskConical,
  Headphones,
  PenTool,
  Plus,
  RefreshCw,
  Server,
  ShieldAlert,
  ShieldCheck,
  Target,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-react';

export interface AgentTemplate {
  id: string;
  name: string;
  type: string;
  industry: string;
  description: string;
  features: string[];
  // Model id from the gateway (ex: "openai/gpt-4o"). This can be overridden at deploy-time.
  model: string;
  platform: string;
  budget: number;
  price: string;
  icon: React.ElementType;
  color: string;
  roi?: string;
  complexity?: 'Basic' | 'Advanced' | 'Expert';
}

export const AGENT_TEMPLATE_INDUSTRIES = [
  'all',
  'E-commerce',
  'B2B',
  'Enterprise',
  'Legal',
  'Banking',
  'Technology',
  'Healthcare',
  'Finance',
] as const;

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: '1',
    name: 'Support Agent',
    type: 'customer_support',
    industry: 'E-commerce',
    description: 'AI-powered customer support agent for handling inquiries, order tracking, and common questions.',
    features: ['Order Status Lookup', 'Refund Processing', 'Product Information', 'FAQ Automation', 'Escalation Routing'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 2000,
    price: '₹25,000/month',
    icon: Headphones,
    color: 'blue',
  },
  {
    id: '2',
    name: 'Sales Agent',
    type: 'sales',
    industry: 'B2B',
    description: 'Intelligent sales assistant for lead qualification, demo scheduling, and product recommendations.',
    features: ['Lead Qualification', 'Demo Scheduling', 'Product Recommendations', 'CRM Integration', 'Follow-up Automation'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 3000,
    price: '₹35,000/month',
    icon: Target,
    color: 'green',
  },
  {
    id: '3',
    name: 'HR Agent',
    type: 'hr',
    industry: 'Enterprise',
    description: 'HR assistant for employee onboarding, policy queries, and leave management.',
    features: ['Employee Onboarding', 'Policy FAQ', 'Leave Management', 'Benefits Information', 'Performance Reviews'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 1500,
    price: '₹20,000/month',
    icon: Users,
    color: 'purple',
  },
  {
    id: '4',
    name: 'Legal Agent',
    type: 'legal',
    industry: 'Legal',
    description: 'Legal document assistant for contract review, compliance checking, and risk assessment.',
    features: ['Contract Review', 'Compliance Check', 'Risk Assessment', 'Document Summarization', 'Clause Analysis'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 5000,
    price: '₹50,000/month',
    icon: ShieldCheck,
    color: 'red',
  },
  {
    id: '5',
    name: 'Finance Agent',
    type: 'finance',
    industry: 'Banking',
    description: 'Financial services bot for account queries, loan applications, and transaction support.',
    features: ['Account Queries', 'Loan Applications', 'Transaction Support', 'Fraud Detection', 'Compliance Verification'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 4000,
    price: '₹45,000/month',
    icon: Wallet,
    color: 'amber',
  },
  {
    id: '6',
    name: 'IT Support Agent',
    type: 'it_support',
    industry: 'Technology',
    description: 'IT helpdesk agent for ticket creation, troubleshooting, and knowledge base access.',
    features: ['Ticket Creation', 'Troubleshooting Guide', 'Password Reset', 'System Status', 'Knowledge Base'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 1800,
    price: '₹22,000/month',
    icon: Server,
    color: 'cyan',
  },
  {
    id: '7',
    name: 'Healthcare Agent',
    type: 'healthcare',
    industry: 'Healthcare',
    description: 'Patient triage assistant for appointment scheduling, symptom assessment, and provider matching.',
    features: ['Appointment Scheduling', 'Symptom Triage', 'Provider Matching', 'Insurance Verification', 'Follow-up Care'],
    model: 'google/gemini-2.0-flash-001',
    platform: 'Google',
    budget: 4500,
    price: '₹55,000/month',
    icon: FlaskConical,
    color: 'emerald',
  },
  {
    id: '8',
    name: 'Refund Agent',
    type: 'refund',
    industry: 'E-commerce',
    description: 'Specialized refund processing agent with fraud detection and approval workflows.',
    features: ['Fraud Detection', 'Refund Approval', 'Policy Enforcement', 'Manual Review Queue', 'Audit Trail'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 2500,
    price: '₹30,000/month',
    icon: RefreshCw,
    color: 'orange',
  },
  {
    id: '9',
    name: 'Onboarding Agent',
    type: 'onboarding',
    industry: 'Enterprise',
    description: 'New employee onboarding agent for paperwork, training, and welcome communications.',
    features: ['Document Collection', 'Training Modules', 'Welcome Sequences', 'Progress Tracking', 'Manager Alerts'],
    model: 'anthropic/claude-3-haiku',
    platform: 'Anthropic',
    budget: 1000,
    price: '₹15,000/month',
    icon: UserPlus,
    color: 'teal',
  },
  {
    id: '10',
    name: 'Compliance Agent',
    type: 'compliance',
    industry: 'Finance',
    description: 'Regulatory compliance monitor for KYC/AML, audit trails, and policy enforcement.',
    features: ['KYC Verification', 'AML Screening', 'Audit Trails', 'Policy Enforcement', 'Risk Alerts'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹65,000/month',
    icon: ShieldAlert,
    color: 'rose',
    roi: 'Reduces compliance risk by 95%',
    complexity: 'Advanced',
  },
  {
    id: '11',
    name: 'Marketing & Content Agent',
    type: 'marketing',
    industry: 'E-commerce',
    description: 'Creative assistant for SEO optimization, social media drafting, and blog post generation.',
    features: ['SEO Optimization', 'Social Media Drafting', 'Blog Post Generation', 'Copy Reviewing', 'Keyword Research'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 3000,
    price: '₹35,000/month',
    icon: PenTool,
    color: 'pink',
    roi: 'Boosts content pipeline output by 3x',
    complexity: 'Basic',
  },
  {
    id: '12',
    name: 'Data Analyst Agent',
    type: 'data_analysis',
    industry: 'Enterprise',
    description: 'Analytical engine for SQL querying, data visualization, and predictive modeling.',
    features: ['SQL Querying', 'Data Visualization', 'Report Generation', 'Trend Analysis', 'Predictive Modeling'],
    model: 'openai/gpt-4o',
    platform: 'OpenAI',
    budget: 5000,
    price: '₹50,000/month',
    icon: Database,
    color: 'indigo',
    roi: 'Accelerates data reporting to real-time',
    complexity: 'Expert',
  },
  {
    id: '13',
    name: 'Software Developer Agent',
    type: 'engineering',
    industry: 'Technology',
    description: 'Coding assistant for PR reviews, bug detection, and code scaffolding.',
    features: ['PR Reviews', 'Bug Detection', 'Documentation Generation', 'Code Scaffolding', 'Refactoring'],
    model: 'anthropic/claude-3-5-sonnet',
    platform: 'Anthropic',
    budget: 6000,
    price: '₹60,000/month',
    icon: Code,
    color: 'sky',
    roi: 'Increases developer throughput by 40%',
    complexity: 'Expert',
  },
  {
    id: 'custom',
    name: 'Create Custom Agent',
    type: 'custom',
    industry: 'All',
    description: 'Build your own specialized AI agent from scratch with custom instructions, tools, and selected models.',
    features: ['Custom System Prompt', 'Any Supported Model', 'Custom Tool Integrations', 'Domain Specific Knowledge', 'Custom Sandbox'],
    model: 'openai/gpt-4o-mini',
    platform: 'OpenAI',
    budget: 0,
    price: 'Pay as you go',
    icon: Plus,
    color: 'slate',
    roi: 'Tailored perfectly for your use case',
    complexity: 'Advanced',
  },
];

